import { Update } from ".";

export const UPDATES_2016_PARTIES: Update[] = [
  {
    date: '2016-01-20',
    temp: {
      party: {
        partyName: 'Prehistoric Party 2016',
        partyIcon: 'party',
        rooms: {
          party1: 'archives:RoomsParty1-PrehistoricParty2016.swf',
          dock: 'archives:RoomsDock-PrehistoricParty2016.swf',
          party19: 'archives:RoomsParty19-PrehistoricParty2016.swf',
          party25: 'archives:RoomsParty25-PrehistoricParty2016.swf',
          party13: 'archives:RoomsParty13-PrehistoricParty2016.swf',
          party14: 'archives:RoomsParty14-PrehistoricParty2016.swf',
          party26: 'archives:RoomsParty26-PrehistoricParty2016.swf',
          party15: 'archives:RoomsParty15-PrehistoricParty2016.swf',
          party23: 'archives:RoomsParty23-PrehistoricParty2016.swf',
          party21: 'archives:RoomsParty21-PrehistoricParty2016.swf',
          party24: 'archives:RoomsParty24-PrehistoricParty2016.swf',
          party16: 'archives:RoomsParty16-PrehistoricParty2016.swf',
          party18: 'archives:RoomsParty18-PrehistoricParty2016.swf',
          party3: 'archives:RoomsParty3-PrehistoricParty2016.swf',
          party20: 'archives:RoomsParty20-PrehistoricParty2016.swf',
          party17: 'archives:RoomsParty17-PrehistoricParty2016.swf',
          party22: 'archives:RoomsParty22-PrehistoricParty2016.swf'
        },
        music: {
          party1: 1061,
          dock: 5000,
          party19: 1095,
          party25: 1103,
          party13: 1092,
          party14: 1096,
          party26: 1104,
          party15: 1093,
          party23: 1101,
          party21: 1100,
          party24: 1102,
          party16: 1094,
          party18: 1098,
          party20: 1099,
          party17: 1097,
          party22: 1104
        },
        mapNote: 'archives:ENClose_upsParty_map_note-PrehistoricParty2016.swf',
        localChanges: {
          'catalogues/login.swf': { en: 'archives:Close_ups160106_character_dialogue_catalog_login.swf' },
          'close_ups/quest_interface.swf': { en: 'archives:Close_upsQuest_interface-PrehistoricParty2016.swf' },
          'close_ups/party_map.swf': { en: 'archives:ENClose_upsParty_map-PrehistoricParty2016.swf' }
        },
        globalChanges: {
          'membership/party1.swf': 'archives:MembershipParty1-PrehistoricParty2016.swf',
          'membership/party2.swf': 'archives:MembershipParty2-PrehistoricParty2016.swf',
          'membership/party3.swf': 'archives:MembershipParty3-PrehistoricParty2016.swf',
          'content/party_icon.swf': 'archives:ContentParty_icon-PrehistoricParty2016.swf',
          'close_ups/160113_character_dialogue_party_leadup.swf': 'archives:Close_ups160113_character_dialogue_party_leadup.swf',
          'close_ups/160120_character_dialogue_party_login.swf': 'archives:Close_ups160120_character_dialogue_party_login-PrehistoricParty2016.swf',
          'close_ups/character_dialogue_login.swf': 'archives:Close_ups160130_character_dialogue_login4-PrehistoricParty2016.swf',
          'content/features.swf': 'archives:ContentFeatures-PrehistoricParty2016.swf',
          'content/logo.swf': 'archives:ContentLogo-PrehistoricParty2016.swf'
        },
        fileChanges: {
          'play/v2/client/interface.swf': 'archives:ClientInterface-PrehistoricParty2016.swf',
          'play/v2/content/global/avatar/sprites/raptorblack.swf': 'archives:AvatarSpritesRaptorBlack.swf',
          'play/v2/content/global/avatar/sprites/pteranodonblue.swf': 'archives:AvatarSpritesPteranodonBlue.swf',
          'play/v2/content/global/avatar/sprites/trexbrown.swf': 'archives:AvatarSpritesTrexBrown.swf',
          'play/v2/content/global/avatar/sprites/triceratopsbrown.swf': 'archives:AvatarSpritesTriceratopsBrown.swf',
          'play/v2/content/global/avatar/sprites/stegosauruspurple.swf': 'archives:AvatarSpritesStegosaurusPurple.swf',
          'play/v2/content/global/rooms/effects/avatar.swf': 'archives:RoomsEffectsAvatar-PrehistoricParty2016.swf',
          'play/v2/client/party.swf': 'archives:ClientParty-PrehistoricParty2016.swf'
        }
      }
    }
  },
  { date: '2016-02-03', end: [ 'party' ] },
  {
    date: '2016-02-10',
    temp: {
      party: {
        partyName: 'Operation: Tri-umph',
        partyIcon: 'party',
        rooms: {
          forts: 'archives:RoomsForts-OperationDoom.swf',
          town: 'archives:RoomsTown-OperationDoom.swf',
          mall: 'archives:RoomsMall-OperationDoom.swf',
          pizza: 'archives:RoomsPizza-OperationDoom.swf',
          plaza: 'archives:RoomsPlaza-OperationDoom.swf',
          party1: 'archives:RoomsParty1-OperationDoom.swf',
          party2: 'archives:RoomsParty2-OperationDoom.swf',
          party3: 'archives:RoomsParty3-OperationDoom.swf',
          party4: 'archives:RoomsParty4-OperationDoom.swf',
          party5: 'archives:RoomsParty5-OperationDoom.swf',
          party6: 'archives:RoomsParty6-OperationDoom.swf',
          party7: 'archives:RoomsParty7-OperationDoom.swf',
          party8: 'archives:RoomsParty8-OperationDoom.swf',
          party9: 'archives:RoomsParty9-OperationDoom.swf',
          party10: 'archives:RoomsParty10-OperationDoom.swf',
          party11: 'archives:RoomsParty11-OperationDoom.swf',
          party12: 'archives:RoomsParty12-OperationDoom.swf'
        },
        music: {
          forts: 1105,
          town: 1109,
          mall: 1106,
          pizza: 1107,
          plaza: 1108,
          party1: 899,
          party2: 899,
          party3: 899,
          party4: 899,
          party5: 899,
          party6: 899,
          party7: 899,
          party8: 899,
          party9: 899,
          party10: 899,
          party11: 1110,
          party12: 901
        },
        localChanges: {
          'close_ups/quest_interface.swf': { en: 'archives:Close_upsQuest_interface-OperationDoom_2.swf' },
          'close_ups/maze_map.swf': { en: 'archives:ENClose_upsMaze_map-OperationDoom.swf' }
        },
        globalChanges: {
          'membership/party1.swf': 'archives:MembershipParty1-OperationDoom.swf',
          'content/party_icon.swf': 'archives:ContentParty_icon-OperationDoom.swf',
          'close_ups/character_dialogue_login.swf': 'archives:Close_ups160224_character_dialogue_login_herbert-OperationDoom_2.swf',
          'close_ups/160210_character_dialogue_rookie.swf': 'archives:Close_ups160210_character_dialogue_rookie-OperationDoom.swf',
          'close_ups/160210_items.swf': 'archives:Close_ups160210_items-OperationDoom.swf',
          'close_ups/160210_items_operationdoom_2.swf': 'archives:Close_ups160210_items-OperationDoom_2.swf',
          'close_ups/160217_character_dialogue_rookie.swf': 'archives:Close_ups160217_character_dialogue_rookie-OperationDoom.swf',
          'close_ups/160217_character_dialogue_rookie_operationdoom_2.swf': 'archives:Close_ups160217_character_dialogue_rookie-OperationDoom_2.swf',
          'close_ups/160217_items.swf': 'archives:Close_ups160217_items-OperationDoom.swf',
          'close_ups/160217_items_operationdoom_2.swf': 'archives:Close_ups160217_items-OperationDoom_2.swf',
          'close_ups/160224_character_dialogue_rookie.swf': 'archives:Close_ups160224_character_dialogue_rookie-OperationDoom.swf',
          'close_ups/160224_character_dialogue_rookie_operationdoom_2.swf': 'archives:Close_ups160224_character_dialogue_rookie-OperationDoom_2.swf',
          'close_ups/160224_items.swf': 'archives:Close_ups160224_items-OperationDoom.swf',
          'close_ups/160224_items_operationdoom_2.swf': 'archives:Close_ups160224_items-OperationDoom_2.swf',
          'close_ups/160224_character_dialogue_herbert_maze.swf': 'archives:Close_ups160224_character_dialogue_herbert_maze-OperationDoom.swf',
          'close_ups/160224_character_dialogue_congrats1.swf': 'archives:Close_ups160224_character_dialogue_congrats1-OperationDoom.swf',
          'close_ups/160224_character_dialogue_congrats1_operationdoom_2.swf': 'archives:Close_ups160224_character_dialogue_congrats1-OperationDoom_2.swf',
          'close_ups/160224_congrats_items.swf': 'archives:Close_ups160224_congrats_items-OperationDoom.swf',
          'close_ups/160224_congrats_items_operationdoom_2.swf': 'archives:Close_ups160224_congrats_items-OperationDoom_2.swf',
          'close_ups/maze_map.swf': 'archives:Close_upsRUMaze_Map-CaveMaze.swf',
          'content/features.swf': 'archives:ContentFeatures-OperationDoom.swf',
          'content/logo.swf': 'archives:ContentLogo-OperationDoom.swf',
          'content/logo_operationdoom_2.swf': 'archives:ContentLogo-OperationDoom_2.swf'
        },
        fileChanges: {
          'play/v2/client/interface.swf': 'archives:ClientInterface-OperationDoom.swf',
          'play/v2/client/party.swf': 'archives:ClientParty-OperationDoom.swf'
        }
      }
    }
  },
  { date: '2016-03-02', end: [ 'party' ] },
  {
    date: '2016-03-16',
    temp: {
      party: {
        partyName: 'Puffle Party 2016',
        partyIcon: 'party',
        rooms: {
          beach: 'archives:RoomsBeach-PuffleParty2016.swf',
          shop: 'archives:RoomsShop-PuffleParty2016.swf',
          coffee: 'archives:RoomsCoffee-PuffleParty2016.swf',
          cove: 'archives:RoomsCove-PuffleParty2016.swf',
          dock: 'archives:RoomsDock-PuffleParty2016.swf',
          forest: 'archives:RoomsForest-PuffleParty2016.swf',
          rink: 'archives:RoomsRink-PuffleParty2016.swf',
          light: 'archives:RoomsLight-PuffleParty2016.swf',
          mall: 'archives:RoomsMall-PuffleParty2016.swf',
          plaza: 'archives:RoomsPlaza-PuffleParty2016.swf',
          forts: 'archives:RoomsForts-PuffleParty2016.swf',
          town: 'archives:RoomsTown-PuffleParty2016.swf',
          dance: 'archives:RoomsDance-PuffleParty2016.swf',
          pizza: 'archives:RoomsPizza-PuffleParty2016.swf'
        },
        music: {
          beach: 651,
          shop: 885,
          coffee: 886,
          cove: 653,
          dock: 888,
          forest: 665,
          rink: 661,
          light: 657,
          mall: 895,
          plaza: 893,
          forts: 656,
          town: 896,
          dance: 664,
          pizza: 892
        },
        localChanges: {
          'close_ups/quest_interface.swf': { en: 'archives:Close_upsQuest_interface-PuffleParty2016.swf' }
        },
        globalChanges: {
          'membership/party1.swf': 'archives:MembershipParty1-PuffleParty2016.swf',
          'membership/party2.swf': 'archives:MembershipParty2-PuffleParty2016.swf',
          'membership/party3.swf': 'archives:MembershipParty3-PuffleParty2016.swf',
          'content/party_icon.swf': 'archives:ContentParty_icon-PuffleParty2016.swf',
          'close_ups/character_dialogue_login.swf': 'archives:Close_ups160316_Character_dialogue_login-PuffleParty2016.swf',
          'close_ups/0316_character_dialogue_red.swf': 'archives:Close_ups0316_Character_dialogue_red-PuffleParty2016.swf',
          'close_ups/0316_character_dialogue_blue.swf': 'archives:Close_ups0316_Character_dialogue_blue-PuffleParty2016.swf',
          'close_ups/0316_character_dialogue_green.swf': 'archives:Close_ups0316_Character_dialogue_green-PuffleParty2016.swf',
          'close_ups/0316_character_dialogue_yellow.swf': 'archives:Close_ups0316_Character_dialogue_yellow-PuffleParty2016.swf',
          'close_ups/0316_character_dialogue_pink.swf': 'archives:Close_ups0316_Character_dialogue_pink-PuffleParty2016.swf',
          'close_ups/0316_character_dialogue_orange.swf': 'archives:Close_ups0316_Character_dialogue_orange-PuffleParty2016.swf',
          'close_ups/0316_character_dialogue_purple.swf': 'archives:Close_ups0316_Character_dialogue_purple-PuffleParty2016.swf',
          'close_ups/0316_character_dialogue_black.swf': 'archives:Close_ups0316_Character_dialogue_black-PuffleParty2016.swf',
          'close_ups/0316_character_dialogue_white.swf': 'archives:Close_ups0316_Character_dialogue_white-PuffleParty2016.swf',
          'close_ups/0316_character_dialogue_brown.swf': 'archives:Close_ups0316_Character_dialogue_brown-PuffleParty2016.swf',
          'close_ups/0316_character_dialogue_rainbow.swf': 'archives:Close_ups0316_Character_dialogue_rainbow-PuffleParty2016.swf',
          'close_ups/0316_character_dialogue_gold.swf': 'archives:Close_ups0316_Character_dialogue_gold-PuffleParty2016.swf',
          'close_ups/puffle_adoption_prompt.swf': 'archives:Close_upsPuffle_adoption_prompt-PuffleParty2016.swf',
          'close_ups/transformation_prompt.swf': 'archives:Close_upsTransformation_prompt-PuffleParty2016.swf',
          'content/features.swf': 'archives:ContentFeatures-PuffleParty2016.swf',
          'content/logo.swf': 'archives:ContentLogo-PuffleParty2016.swf',
          'content/prompts.swf': 'archives:ContentPrompts-PuffleParty2016.swf'
        },
        fileChanges: {
          'play/v2/client/interface.swf': 'archives:ClientInterface-PuffleParty2016.swf',
          'play/v2/content/global/avatar/sprites/puffleblue.swf': 'archives:AvatarSpritesPuffleBlue-PuffleParty2016.swf',
          'play/v2/content/global/avatar/sprites/pufflered.swf': 'archives:AvatarSpritesPuffleRed-PuffleParty2016.swf',
          'play/v2/content/global/avatar/sprites/pufflepink.swf': 'archives:AvatarSpritesPufflePink-PuffleParty2016.swf',
          'play/v2/content/global/avatar/sprites/puffleblack.swf': 'archives:AvatarSpritesPuffleBlack-PuffleParty2016.swf',
          'play/v2/content/global/avatar/sprites/pufflegreen.swf': 'archives:AvatarSpritesPuffleGreen-PuffleParty2016.swf',
          'play/v2/content/global/avatar/sprites/pufflepurple.swf': 'archives:AvatarSpritesPufflePurple-PuffleParty2016.swf',
          'play/v2/content/global/avatar/sprites/puffleyellow.swf': 'archives:AvatarSpritesPuffleYellow-PuffleParty2016.swf',
          'play/v2/content/global/avatar/sprites/pufflewhite.swf': 'archives:AvatarSpritesPuffleWhite-PuffleParty2016.swf',
          'play/v2/content/global/avatar/sprites/puffleorange.swf': 'archives:AvatarSpritesPuffleOrange-PuffleParty2016.swf',
          'play/v2/content/global/avatar/sprites/pufflebrown.swf': 'archives:AvatarSpritesPuffleBrown-PuffleParty2016.swf',
          'play/v2/content/global/avatar/sprites/pufflegold.swf': 'archives:AvatarSpritesPuffleGold.swf',
          'play/v2/content/global/avatar/sprites/pufflerainbow.swf': 'archives:AvatarSpritesPuffleRainbow-PuffleParty2016.swf',
          'play/v2/content/global/avatar/sprites/puffledog.swf': 'archives:AvatarSpritesPuffleDog.swf',
          'play/v2/content/global/avatar/sprites/pufflecat.swf': 'archives:AvatarSpritesPuffleCat.swf',
          'play/v2/client/party.swf': 'archives:ClientParty-PuffleParty2016.swf'
        }
      }
    }
  },
  { date: '2016-04-06', end: [ 'party' ] },
  {
    date: '2016-04-20',
    temp: {
      party: {
        partyName: 'Wilderness Expedition',
        partyIcon: 'party',
        rooms: {
          dock: 'archives:RoomsDock-WildernessExpedition2016.swf',
          party1: 'archives:RoomsParty1-WildernessExpedition2016.swf',
          party2: 'archives:RoomsParty2-WildernessExpedition2016.swf',
          party3: 'archives:RoomsParty3-WildernessExpedition2016.swf',
          party4: 'archives:RoomsParty4-WildernessExpedition2016.swf',
          party5: 'archives:RoomsParty5-WildernessExpedition2016.swf',
          party6: 'archives:RoomsParty6-WildernessExpedition2016.swf',
          party7: 'archives:RoomsParty7-WildernessExpedition2016.swf',
          party8: 'archives:RoomsParty8-WildernessExpedition2016.swf',
          party9: 'archives:RoomsParty9-WildernessExpedition2016.swf'
        },
        music: {
          dock: 1115,
          party1: 1114,
          party2: 1114,
          party3: 1114,
          party4: 1113,
          party5: 1113,
          party6: 1113,
          party7: 1112,
          party8: 1112,
          party9: 1111
        },
        localChanges: {
          'close_ups/quest_interface.swf': { en: 'archives:Close_upsQuest_interface-WildernessExpedition2016.swf' }
        },
        globalChanges: {
          'membership/party1.swf': 'archives:MembershipParty1-WildernessExpedition2016.swf',
          'content/interface.swf': 'archives:ContentInterface-WildernessExpedition2016.swf',
          'content/party_icon.swf': 'archives:ContentParty_icon-WildernessExpedition2016.swf',
          'close_ups/character_dialogue_login.swf': 'archives:Close_ups160420_character_dialogue_login-WildernessExpedition2016.swf',
          'close_ups/160420_character_dialogue_fishing_start.swf': 'archives:Close_ups160420_character_dialogue_fishing_start-WildernessExpedition2016.swf',
          'close_ups/160420_character_dialogue_music_start.swf': 'archives:Close_ups160420_character_dialogue_music_start-WildernessExpedition2016.swf',
          'close_ups/160420_character_dialogue_camo_start.swf': 'archives:Close_ups160420_character_dialogue_camo_start-WildernessExpedition2016.swf',
          'close_ups/160420_character_dialogue_wood_start.swf': 'archives:Close_ups160420_character_dialogue_wood_start-WildernessExpedition2016.swf',
          'close_ups/160420_character_dialogue_tracking_congrats.swf': 'archives:Close_ups160420_character_dialogue_tracking_congrats-WildernessExpedition2016.swf',
          'close_ups/160420_character_dialogue_fishing_congrats.swf': 'archives:Close_ups160420_character_dialogue_fishing_congrats-WildernessExpedition2016.swf',
          'close_ups/160420_character_dialogue_music_congrats.swf': 'archives:Close_ups160420_character_dialogue_music_congrats-WildernessExpedition2016.swf',
          'close_ups/160420_character_dialogue_camo_congrats.swf': 'archives:Close_ups160420_character_dialogue_camo_congrats-WildernessExpedition2016.swf',
          'close_ups/160420_character_dialogue_wood_congrats.swf': 'archives:Close_ups160420_character_dialogue_wood_congrats-WildernessExpedition2016.swf',
          'close_ups/160420_character_dialogue_village_congrats.swf': 'archives:Close_ups160420_character_dialogue_village_congrats-WildernessExpedition2016.swf',
          'close_ups/160420_character_dialogue_final_congrats.swf': 'archives:Close_ups160420_character_dialogue_final_congrats-WildernessExpedition2016.swf',
          'close_ups/160420_mazenote.swf': 'archives:Close_ups160420_mazenote-WildernessExpedition2016.swf',
          'content/features.swf': 'archives:ContentFeatures-WildernessExpedition2016.swf',
          'content/logo.swf': 'archives:ContentLogo-WildernessExpedition2016.swf',
          'content/prompts.swf': 'archives:ContentPrompts-WildernessExpedition2016.swf'
        },
        fileChanges: {
          'play/v2/client/interface.swf': 'archives:ClientInterface-WildernessExpedition2016.swf',
          'play/v2/client/party.swf': 'archives:ClientParty-WildernessExpedition2016.swf'
        }
      }
    }
  },
  { date: '2016-05-04', end: [ 'party' ] },
  {
    date: '2016-05-18',
    temp: {
      party: {
        partyName: 'Zootopia Party',
        partyIcon: 'party',
        rooms: {
          plaza: 'archives:RoomsPlaza-ZootopiaParty.swf',
          forts: 'archives:RoomsForts-ZootopiaParty.swf',
          town: 'archives:RoomsTown-ZootopiaParty.swf',
          party1: 'archives:RoomsParty1-ZootopiaParty.swf',
          coffee: 'archives:RoomsCoffee-ZootopiaParty.swf',
          dock: 'archives:RoomsDock-ZootopiaParty.swf',
          forest: 'archives:RoomsForest-ZootopiaParty.swf',
          rink: 'archives:RoomsRink-ZootopiaParty.swf'
        },
        music: {
          plaza: 1121,
          forts: 1119,
          town: 1123,
          party1: 1120,
          coffee: 1117,
          dock: 1116,
          forest: 1118,
          rink: 1122
        },
        localChanges: {
          'close_ups/quest_interface.swf': { en: 'archives:Close_upsQuest_interface-ZootopiaParty.swf' }
        },
        globalChanges: {
          'membership/party1.swf': 'archives:MembershipParty1-ZootopiaParty.swf',
          'content/interface.swf': 'archives:ContentInterface-ZootopiaParty.swf',
          'content/party_icon.swf': 'archives:ContentParty_icon-ZootopiaParty.swf',
          'close_ups/character_dialogue_login.swf': 'archives:Close_ups160629_character_dialogue_login-ZootopiaParty.swf',
          'content/features.swf': 'archives:ContentFeatures-ZootopiaParty.swf',
          'content/logo.swf': 'archives:ContentLogo-ZootopiaParty.swf',
          'content/prompts.swf': 'archives:ContentPrompts-ZootopiaParty.swf'
        }
      }
    }
  },
  {
    date: '2016-07-06',
    end: [ 'party' ],
    temp: {
      party2: {
        partyName: 'Finding Dory Party',
        partyIcon: 'party',
        rooms: {
          beach: 'archives:RoomsBeach-FindingDoryParty.swf',
          cove: 'archives:RoomsCove-FindingDoryParty.swf',
          dock: 'archives:RoomsDock-FindingDoryParty.swf',
          berg: 'archives:RoomsBerg-FindingDoryParty.swf',
          party1: 'archives:RoomsParty1-FindingDoryParty.swf',
          town: 'archives:RoomsTown-FindingDoryParty.swf'
        },
        music: { beach: 1124, cove: 1129, dock: 1126, berg: 1125, party1: 1127, town: 1128 },
        localChanges: {
          'close_ups/quest_interface.swf': { en: 'archives:Close_upsQuest_interface-FindingDoryParty.swf' }
        },
        globalChanges: {
          'membership/party1.swf': 'archives:MembershipParty1-FindingDoryParty.swf',
          'content/interface.swf': 'archives:ContentInterface-FindingDoryParty.swf',
          'content/party_icon.swf': 'archives:ContentParty_icon-FindingDoryParty.swf',
          'close_ups/character_dialogue_login.swf': 'archives:Close_ups160706_character_dialogue_login.swf-FindingDoryParty.swf',
          'close_ups/160706_character_dialogue_task0_start.swf': 'archives:Close_ups160706_character_dialogue_task0_start-FindingDoryParty.swf',
          'close_ups/160706_character_dialogue_task0_congrats.swf': 'archives:Close_ups160706_character_dialogue_task0_congrats-FindingDoryParty.swf',
          'close_ups/160706_character_dialogue_task1_start.swf': 'archives:Close_ups160706_character_dialogue_task1_start-FindingDoryParty.swf',
          'close_ups/160706_character_dialogue_task1_congrats.swf': 'archives:Close_ups160706_character_dialogue_task1_congrats-FindingDoryParty.swf',
          'close_ups/160706_character_dialogue_task2_start.swf': 'archives:Close_ups160706_character_dialogue_task2_start-FindingDoryParty.swf',
          'close_ups/160706_character_dialogue_task2_congrats.swf': 'archives:Close_ups160706_character_dialogue_task2_congrats-FindingDoryParty.swf',
          'close_ups/160706_character_dialogue_task3_start.swf': 'archives:Close_ups160706_character_dialogue_task3_start-FindingDoryParty.swf',
          'close_ups/160706_character_dialogue_task3_congrats.swf': 'archives:Close_ups160706_character_dialogue_task3_congrats-FindingDoryParty.swf',
          'close_ups/160706_character_dialogue_task4_start.swf': 'archives:Close_ups160706_character_dialogue_task4_start-FindingDoryParty.swf',
          'close_ups/160706_character_dialogue_task4_congrats.swf': 'archives:Close_ups160706_character_dialogue_task4_congrats-FindingDoryParty.swf',
          'close_ups/160706_character_dialogue_task5_start.swf': 'archives:Close_ups160706_character_dialogue_task5_start-FindingDoryParty.swf',
          'close_ups/160706_character_dialogue_task5_congrats.swf': 'archives:Close_ups160706_character_dialogue_task5_congrats-FindingDoryParty.swf',
          'close_ups/160706_character_dialogue_task6_start.swf': 'archives:Close_ups160706_character_dialogue_task6_start-FindingDoryParty.swf',
          'close_ups/160706_character_dialogue_task6_congrats.swf': 'archives:Close_ups160706_character_dialogue_task6_congrats-FindingDoryParty.swf',
          'close_ups/160706_character_dialogue_task7_start.swf': 'archives:Close_ups160706_character_dialogue_task7_start-FindingDoryParty.swf',
          'close_ups/160706_character_dialogue_task7_congrats.swf': 'archives:Close_ups160706_character_dialogue_task7_congrats-FindingDoryParty.swf',
          'close_ups/160706_character_dialogue_final_congrats.swf': 'archives:Close_ups160706_character_dialogue_final_congrats.swf-FindingDoryParty.swf',
          'content/features.swf': 'archives:ContentFeatures-FindingDoryParty.swf',
          'content/logo.swf': 'archives:ContentLogo-FindingDoryParty.swf',
          'content/party.swf': 'archives:ContentParty-FindingDoryParty.swf',
          'content/prompts.swf': 'archives:ContentPrompts-FindingDoryParty.swf'
        }
      }
    }
  },
  {
    date: '2016-08-17',
    end: [ 'party2' ],
    temp: {
      party: {
        partyName: 'Frozen Fever Party',
        partyIcon: 'party',
        rooms: {
          beach: 'archives:RoomsBeach-FrozenFeverParty.swf',
          cove: 'archives:RoomsCove-FrozenFeverParty.swf',
          dock: 'archives:RoomsDock-FrozenFeverParty2016.swf',
          forest: 'archives:RoomsForest-FrozenFeverParty.swf',
          party1: 'archives:RoomsParty1-FrozenFeverParty.swf',
          party2: 'archives:RoomsParty2-FrozenFeverParty.swf',
          plaza: 'archives:RoomsPlaza-FrozenFeverParty2016.swf',
          forts: 'archives:RoomsForts-FrozenFeverParty2016.swf',
          town: 'archives:RoomsTown-FrozenFeverParty2016.swf',
          partysolo1: 'archives:RoomsConcertElsaconcert-FrozenFeverParty.swf'
        },
        music: {
          beach: 1133,
          cove: 909,
          dock: 1131,
          forest: 908,
          party1: 739,
          party2: 1134,
          plaza: 1130,
          forts: 1135,
          town: 1132,
          partysolo1: 739
        },
        map: 'archives:ContentMap-FrozenFeverParty2016.swf',
        localChanges: {
          'close_ups/quest_interface.swf': { en: 'archives:ENClose_upsQuest_interface-FrozenFeverParty2016.swf' }
        },
        globalChanges: {
          'membership/party1.swf': 'archives:MembershipParty1-FrozenFeverParty.swf',
          'content/interface.swf': 'archives:ContentInterface-FrozenFeverParty2016.swf',
          'content/party_icon.swf': 'archives:ContentParty_icon-FrozenFeverParty.swf',
          'close_ups/character_dialogue_login.swf': 'archives:Close_upsCharacter_dialogue_login-FrozenFeverParty2016.swf',
          'close_ups/character_dialogue_elsa.swf': 'archives:Close_upsCharacter_dialogue_elsa-FrozenFeverParty.swf',
          'close_ups/ice_palace_locked.swf': 'archives:Close_upsIce_palace_locked-FrozenFeverParty2016.swf',
          'content/logo.swf': 'archives:ContentLogo-FrozenFeverParty.swf',
          'content/party.swf': 'archives:ContentParty-FrozenFeverParty2016.swf'
        },
        fileChanges: {
          'play/v2/content/global/avatar/sprites/olaf.swf': 'archives:AvatarSpritesOlaf.swf',
          'play/v2/content/global/avatar/sprites/marshmallow.swf': 'archives:AvatarSpritesMarshmallow.swf',
          'play/v2/content/global/rooms/effects/avatar.swf': 'archives:RoomsEffectsAvatar-FrozenFeverParty2016.swf'
        }
      }
    }
  },
  {
    date: '2016-09-28',
    end: [ 'party' ],
    temp: {
      party2: {
        partyName: 'Halloween Party 2016',
        partyIcon: 'party',
        rooms: {
          lounge: 'archives:RoomsLounge-HalloweenParty2016.swf',
          beach: 'archives:RoomsBeach-HalloweenParty2016.swf',
          beacon: 'archives:RoomsBeacon-HalloweenParty2016.swf',
          shop: 'archives:RoomsShop-HalloweenParty2016.swf',
          cloudforest: 'archives:Hallo15_cloudforest.swf',
          cove: 'archives:RoomsCove-HalloweenParty2016.swf',
          dock: 'archives:RoomsDock-HalloweenParty2016.swf',
          dojo: 'archives:Hallo15_dojo.swf',
          dojoext: 'archives:RoomsDojoext-HalloweenParty2016.swf',
          agentlobbymulti: 'archives:Hallo15_agentlobbymulti.swf',
          dojofire: 'archives:Hallo15_dojofire.swf',
          forest: 'archives:RoomsForest-HalloweenParty2016.swf',
          rink: 'archives:RoomsRink-HalloweenParty2016.swf',
          berg: 'archives:RoomsBerg-HalloweenParty2016.swf',
          light: 'archives:Hallo15_light.swf',
          attic: 'archives:Hallo15_attic.swf',
          shack: 'archives:RoomsShack-HalloweenParty2016.swf',
          dance: 'archives:Hallo15_dance.swf',
          pet: 'archives:Hallo15_pet.swf',
          pizza: 'archives:Hallo15_pizza.swf',
          plaza: 'archives:RoomsPlaza-HalloweenParty2016.swf',
          mall: 'archives:RoomsMall-HalloweenParty2016.swf',
          hotellobby: 'archives:Hallo15_hotellobby.swf',
          hotelroof: 'archives:Hallo15_hotelroof.swf',
          hotelspa: 'archives:RoomsHotelspa-HalloweenParty2016.swf',
          park: 'archives:Hallo15_park.swf',
          pufflewild: 'archives:Hallo15_pufflewild.swf',
          school: 'archives:RoomsSchool-HalloweenParty2016.swf',
          skatepark: 'archives:RoomsSkatepark-HalloweenParty2016.swf',
          mtn: 'archives:Hallo15_mtn.swf',
          lodge: 'archives:RoomsLodge-HalloweenParty2016.swf',
          village: 'archives:RoomsVillage-HalloweenParty2016.swf',
          dojosnow: 'archives:Hallo15_dojosnow.swf',
          forts: 'archives:RoomsForts-HalloweenParty2016.swf',
          town: 'archives:RoomsTown-HalloweenParty2016.swf',
          cave: 'archives:RoomsCave-HalloweenParty2016.swf'
        },
        music: {
          lounge: 1055,
          beach: 1054,
          beacon: 1053,
          shop: 345,
          cloudforest: 1044,
          cove: 1035,
          dock: 1037,
          dojo: 403,
          dojoext: 1045,
          agentlobbymulti: 922,
          dojofire: 405,
          forest: 1038,
          rink: 1067,
          berg: 1043,
          light: 588,
          attic: 884,
          shack: 1041,
          dance: 1036,
          pet: 659,
          pizza: 1033,
          plaza: 1035,
          mall: 1032,
          hotellobby: 1048,
          hotelroof: 1049,
          hotelspa: 1050,
          park: 1051,
          pufflewild: 1057,
          school: 1040,
          skatepark: 1034,
          mtn: 1042,
          lodge: 1056,
          village: 1042,
          dojosnow: 407,
          forts: 1039,
          town: 1035,
          cave: 532
        },
        localChanges: {
          'close_ups/quest_interface.swf': { en: 'archives:Close_upsQuest_interface-HalloweenParty2016.swf' }
        },
        globalChanges: {
          'membership/party1.swf': 'archives:MembershipParty1-HalloweenParty2016.swf',
          'membership/party2.swf': 'archives:MembershipParty2-HalloweenParty2016.swf',
          'membership/party3.swf': 'archives:MembershipParty3-HalloweenParty2016.swf',
          'content/interface.swf': 'archives:ContentInterface-HalloweenParty2016.swf',
          'content/party_icon.swf': 'archives:ContentParty_icon-HalloweenParty2016.swf',
          'close_ups/character_dialogue_login.swf': 'archives:Close_ups160928_character_dialogue_login-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task0_start.swf': 'archives:Close_ups160928_character_dialogue_task0_start-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task1_start.swf': 'archives:Close_ups160928_character_dialogue_task1_start-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task2_start.swf': 'archives:Close_ups160928_character_dialogue_task2_start-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task3_start.swf': 'archives:Close_ups160928_character_dialogue_task3_start-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task4_start.swf': 'archives:Close_ups160928_character_dialogue_task4_start-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task5_start.swf': 'archives:Close_ups160928_character_dialogue_task5_start-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task6_start.swf': 'archives:Close_ups160928_character_dialogue_task6_start-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task0_congrats.swf': 'archives:Close_ups160928_character_dialogue_task0_congrats-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task1_congrats.swf': 'archives:Close_ups160928_character_dialogue_task1_congrats-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task2_congrats.swf': 'archives:Close_ups160928_character_dialogue_task2_congrats-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task3_congrats.swf': 'archives:Close_ups160928_character_dialogue_task3_congrats-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task4_congrats.swf': 'archives:Close_ups160928_character_dialogue_task4_congrats-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task5_congrats.swf': 'archives:Close_ups160928_character_dialogue_task5_congrats-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task6_congrats.swf': 'archives:Close_ups160928_character_dialogue_task6_congrats-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task7_start.swf': 'archives:Close_ups160928_character_dialogue_task7_start-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task8_start.swf': 'archives:Close_ups160928_character_dialogue_task8_start-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task9_start.swf': 'archives:Close_ups160928_character_dialogue_task9_start-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task11_start.swf': 'archives:Close_ups160928_character_dialogue_task11_start-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task12_start.swf': 'archives:Close_ups160928_character_dialogue_task12_start-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task13_start.swf': 'archives:Close_ups160928_character_dialogue_task13_start-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task14_start.swf': 'archives:Close_ups160928_character_dialogue_task14_start-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task7_congrats.swf': 'archives:Close_ups160928_character_dialogue_task7_congrats-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task8_congrats.swf': 'archives:Close_ups160928_character_dialogue_task8_congrats-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task9_congrats.swf': 'archives:Close_ups160928_character_dialogue_task9_congrats-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task11_congrats.swf': 'archives:Close_ups160928_character_dialogue_task11_congrats-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task12_congrats.swf': 'archives:Close_ups160928_character_dialogue_task12_congrats-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task13_congrats.swf': 'archives:Close_ups160928_character_dialogue_task13_congrats-HalloweenParty2016.swf',
          'close_ups/160928_character_dialogue_task14_congrats.swf': 'archives:Close_ups160928_character_dialogue_task14_congrats-HalloweenParty2016.swf',
          'close_ups/161019_character_dialogue_final_anniversary.swf': 'archives:Close_ups161019_character_dialogue_final_anniversary.swf-HalloweenParty2016.swf',
          'content/features.swf': 'archives:ContentFeatures-HalloweenParty2016.swf',
          'content/logo.swf': 'archives:ContentLogo-HalloweenParty2016.swf',
          'content/party.swf': 'archives:ContentParty-HalloweenParty2016.swf',
          'content/prompts.swf': 'archives:ContentPrompts-HalloweenParty2016.swf',
          'telescope/telescope.swf': 'archives:Telescope-HalloweenParty2016.swf',
          'binoculars/binoculars.swf': 'archives:Binoculars-HalloweenParty2016.swf'
        },
        fileChanges: {
          'play/v2/content/global/avatar/sprites/vampirea.swf': 'archives:AvatarSpritesVampireA-HalloweenParty2013.swf',
          'play/v2/content/global/avatar/sprites/vampireb.swf': 'archives:AvatarSpritesVampireB-HalloweenParty2013.swf',
          'play/v2/content/global/avatar/sprites/vampirec.swf': 'archives:AvatarSpritesVampireC-HalloweenParty2013.swf',
          'play/v2/content/global/avatar/sprites/werewolfa.swf': 'archives:AvatarSpritesWerewolfA-HalloweenParty2013.swf',
          'play/v2/content/global/avatar/sprites/werewolfb.swf': 'archives:AvatarSpritesWerewolfB-HalloweenParty2013.swf',
          'play/v2/content/global/avatar/sprites/werewolfc.swf': 'archives:AvatarSpritesWerewolfC-HalloweenParty2013.swf',
          'play/v2/content/global/avatar/sprites/zombiea.swf': 'archives:AvatarSpritesZombieA-HalloweenParty2013.swf',
          'play/v2/content/global/avatar/sprites/zombieb.swf': 'archives:AvatarSpritesZombieB-HalloweenParty2013.swf',
          'play/v2/content/global/avatar/sprites/zombiec.swf': 'archives:AvatarSpritesZombieC-HalloweenParty2013.swf',
          'play/v2/content/global/rooms/NOTLS-ALL-EN.swf': 'archives:RoomsNOTLS-ALL-EN-HalloweenParty2014.swf'
        }
      }
    }
  },
  {
    date: '2016-10-19',
    temp: {
      party3: {
        partyName: '11th Anniversary Party',
        partyIcon: 'party',
        rooms: {
          coffee: 'archives:RoomsCoffee-11thAnniversaryParty.swf',
          town: 'archives:RoomsTown-11thAnniversaryParty.swf'
        },
        music: { coffee: 763, town: 1035 },
        localChanges: { 'books/year1516.swf': { en: 'archives:ENBooksYear1516.swf' } }
      }
    }
  },
  { date: '2016-10-20', end: [ 'party3' ] },
  {
    date: '2016-11-02',
    end: [ 'party2' ],
    temp: {
      party: {
        partyName: 'Music Jam 2016',
        partyIcon: 'party',
        rooms: {
          lounge: 'archives:RoomsLounge-MusicJam2016.swf',
          party11: 'archives:RoomsParty11-MusicJam2016.swf',
          beach: 'archives:RoomsBeach-MusicJam2016.swf',
          beacon: 'archives:RoomsBeacon-TheFair2015.swf',
          party4: 'archives:RoomsParty4-MusicJam2016.swf',
          party3: 'archives:RoomsParty3-MusicJam2016.swf',
          party7: 'archives:RoomsParty7-MusicJam2016.swf',
          shop: 'archives:RoomsShop-HalloweenParty2016.swf',
          cloudforest: 'archives:RoomsCloudforest-MusicJam2016.swf',
          coffee: 'archives:RoomsCoffee-MusicJam2016.swf',
          cove: 'archives:RoomsCove-MusicJam2016.swf',
          dock: 'archives:RoomsDock-MusicJam2016.swf',
          dojo: 'archives:RoomsDojo-MusicJam2016.swf',
          dojoext: 'archives:RoomsDojoext-MusicJam2016.swf',
          party6: 'archives:RoomsParty6-MusicJam2016.swf',
          party1: 'archives:RoomsParty1-MusicJam2016.swf',
          dojofire: 'archives:RoomsDojofire-MusicJam2016.swf',
          forest: 'archives:RoomsForest-MusicJam2016.swf',
          rink: 'archives:RoomsRink-MusicJam2016.swf',
          berg: 'archives:RoomsBerg-MusicJam2016.swf',
          light: 'archives:RoomsLight-MusicJam2016.swf',
          party9: 'archives:RoomsParty9-MusicJam2016.swf',
          party2: 'archives:RoomsParty2-MusicJam2016.swf',
          mall: 'archives:RoomsMall-MusicJam2016.swf',
          shack: 'archives:RoomsShack-MusicJam2016.swf',
          party8: 'archives:RoomsParty8-MusicJam2016.swf',
          pet: 'archives:RoomsPet-HalloweenParty2014.swf',
          pizza: 'archives:RoomsPizza-MusicJam2016.swf',
          plaza: 'archives:RoomsPlaza-MusicJam2016.swf',
          party5: 'archives:RoomsParty5-MusicJam2016.swf',
          hotelroof: 'archives:RoomsHotelroof-MusicJam2016.swf',
          park: 'archives:RoomsPark-TheFair2015.swf',
          pufflewild: 'archives:RoomsPufflewild-MusicJam2016.swf',
          skatepark: 'archives:RoomsSkatepark-MusicJam2016.swf',
          mtn: 'archives:RoomsMtn-MusicJam2016.swf',
          dojosnow: 'archives:RoomsDojosnow-MusicJam2016.swf',
          forts: 'archives:RoomsForts-MusicJam2016.swf',
          town: 'archives:RoomsTown-MusicJam2016.swf',
          dance: 'archives:RoomsDance-May2015.swf'
        },
        music: {
          lounge: 1148,
          party11: 1143,
          beacon: 583,
          party4: 727,
          party3: 1149,
          party7: 1140,
          shop: 345,
          cloudforest: 363,
          coffee: 429,
          cove: 579,
          dock: 722,
          dojo: 403,
          dojoext: 404,
          party6: 729,
          party1: 724,
          dojofire: 405,
          forest: 1137,
          rink: 1146,
          berg: 584,
          light: 588,
          party9: 1141,
          party2: 1151,
          mall: 1139,
          shack: 580,
          party8: 1150,
          pet: 659,
          pizza: 1144,
          plaza: 1145,
          party5: 728,
          hotelroof: 360,
          park: 658,
          pufflewild: 897,
          skatepark: 754,
          mtn: 590,
          dojosnow: 407,
          forts: 1138,
          town: 1147,
          dance: 1136
        },
        localChanges: {
          'close_ups/quest_interface.swf': { en: 'archives:Close_upsQuest_interface-MusicJam2016.swf' }
        },
        globalChanges: {
          'membership/party1.swf': 'archives:MembershipParty1-MusicJam2016.swf',
          'content/interface.swf': 'archives:ContentInterface-MusicJam2016.swf',
          'content/party_icon.swf': 'archives:ContentParty_icon-MusicJam2016.swf',
          'close_ups/character_dialogue_login.swf': 'archives:Close_ups161102_character_dialogue_login-MusicJam2016.swf',
          'close_ups/161102_character_dialogue_task1_start.swf': 'archives:Close_ups161102_character_dialogue_task1_start-MusicJam2016.swf',
          'close_ups/161102_character_dialogue_task2_start.swf': 'archives:Close_ups161102_character_dialogue_task2_start-MusicJam2016.swf',
          'close_ups/161102_character_dialogue_task3_start.swf': 'archives:Close_ups161102_character_dialogue_task3_start-MusicJam2016.swf',
          'close_ups/161102_character_dialogue_task4_start.swf': 'archives:Close_ups161102_character_dialogue_task4_start-MusicJam2016.swf',
          'close_ups/161102_character_dialogue_task5_start.swf': 'archives:Close_ups161102_character_dialogue_task5_start-MusicJam2016.swf',
          'close_ups/161102_character_dialogue_task6_start.swf': 'archives:Close_ups161102_character_dialogue_task6_start-MusicJam2016.swf',
          'close_ups/161102_character_dialogue_task7_start.swf': 'archives:Close_ups161102_character_dialogue_task7_start-MusicJam2016.swf',
          'close_ups/161102_character_dialogue_task8_start.swf': 'archives:Close_ups161102_character_dialogue_task8_start-MusicJam2016.swf',
          'close_ups/161102_character_dialogue_task1_congrats.swf': 'archives:Close_ups161102_character_dialogue_task1_congrats-MusicJam2016.swf',
          'close_ups/161102_character_dialogue_task2_congrats.swf': 'archives:Close_ups161102_character_dialogue_task2_congrats-MusicJam2016.swf',
          'close_ups/161102_character_dialogue_task3_congrats.swf': 'archives:Close_ups161102_character_dialogue_task3_congrats-MusicJam2016.swf',
          'close_ups/161102_character_dialogue_task4_congrats.swf': 'archives:Close_ups161102_character_dialogue_task4_congrats-MusicJam2016.swf',
          'close_ups/161102_character_dialogue_task5_congrats.swf': 'archives:Close_ups161102_character_dialogue_task5_congrats-MusicJam2016.swf',
          'close_ups/161102_character_dialogue_task6_congrats.swf': 'archives:Close_ups161102_character_dialogue_task6_congrats-MusicJam2016.swf',
          'close_ups/161102_character_dialogue_task7_congrats.swf': 'archives:Close_ups161102_character_dialogue_task7_congrats-MusicJam2016.swf',
          'close_ups/161102_character_dialogue_task8_congrats.swf': 'archives:Close_ups161102_character_dialogue_task8_congrats-MusicJam2016.swf',
          'close_ups/161102_character_dialogue_final_congrats.swf': 'archives:Close_ups161102_character_dialogue_final_congrats.swf-MusicJam2016.swf',
          'content/features.swf': 'archives:ContentFeatures-MusicJam2016.swf',
          'content/logo.swf': 'archives:ContentLogo-MusicJam2016.swf',
          'content/party.swf': 'archives:ContentParty-MusicJam2016.swf',
          'content/prompts.swf': 'archives:ContentPrompts-MusicJam2016.swf',
          'telescope/telescope.swf': 'archives:Telescope-MusicJam2016.swf',
          'binoculars/binoculars.swf': 'archives:Binoculars-MusicJam2016.swf'
        }
      }
    }
  },
  {
    date: '2016-11-30',
    end: [ 'party' ],
    temp: {
      party2: {
        partyName: 'Holiday Party 2016',
        partyIcon: 'party',
        rooms: {
          lounge: 'archives:RoomsLounge-HolidayParty2015.swf',
          beach: 'archives:RoomsBeach-HolidayParty2016.swf',
          beacon: 'archives:RoomsBeacon-HolidayParty2015.swf',
          boiler: 'archives:RoomsBoiler-HolidayParty2016.swf',
          shop: 'archives:RoomsShop-HolidayParty2015.swf',
          cloudforest: 'archives:RoomsCloudforest-HolidayParty2015.swf',
          coffee: 'archives:RoomsCoffee-HolidayParty2016.swf',
          cove: 'archives:RoomsCove-HolidayParty2015.swf',
          shipquarters: 'archives:RoomsShipquarters-HolidayParty2016.swf',
          shipnest: 'archives:RoomsShipnest-HolidayParty2015.swf',
          dock: 'archives:RoomsDock-HolidayParty2016.swf',
          dojo: 'archives:RoomsDojo-HolidayParty2015.swf',
          dojoext: 'archives:RoomsDojoext-HolidayParty2016.swf',
          agentlobbymulti: 'archives:Hallo15_agentlobbymulti.swf',
          dojofire: 'archives:RoomsDojofire-HolidayParty2015.swf',
          forest: 'archives:RoomsForest-HolidayParty2016.swf',
          lake: 'archives:RoomsLake-HolidayParty2016.swf',
          rink: 'archives:RoomsRink-HolidayParty2016.swf',
          berg: 'archives:RoomsBerg-HolidayParty2016.swf',
          light: 'archives:RoomsLight-HolidayParty2016.swf',
          attic: 'archives:RoomsAttic-HolidayParty2015.swf',
          mall: 'archives:RoomsMall-HolidayParty2016.swf',
          ship: 'archives:RoomsShip-HolidayParty2016.swf',
          mine: 'archives:RoomsMine-HolidayParty2016.swf',
          shack: 'archives:RoomsShack-HolidayParty2016.swf',
          dance: 'archives:RoomsDance-HolidayParty2015.swf',
          pet: 'archives:RoomsPet-HolidayParty2015.swf',
          pizza: 'archives:RoomsPizza-HolidayParty2015.swf',
          plaza: 'archives:RoomsPlaza-HolidayParty2016.swf',
          hotelroof: 'archives:RoomsHotelroof-HolidayParty2015.swf',
          hotelspa: 'archives:RoomsHotelspa-HolidayParty2015.swf',
          park: 'archives:RoomsPark-HolidayParty2015.swf',
          pufflewild: 'archives:RoomsPufflewild-HolidayParty2015.swf',
          party13: 'archives:RoomsParty13-HolidayParty2015.swf',
          school: 'archives:RoomsSchool-HolidayParty2015.swf',
          shiphold: 'archives:RoomsShiphold-HolidayParty2016.swf',
          skatepark: 'archives:RoomsSkatepark-HolidayParty2016.swf',
          mtn: 'archives:RoomsMtn-HolidayParty2015.swf',
          lodge: 'archives:RoomsLodge-HolidayParty2016.swf',
          village: 'archives:RoomsVillage-HolidayParty2016.swf',
          dojosnow: 'archives:RoomsDojosnow-HolidayParty2015.swf',
          forts: 'archives:RoomsForts-HolidayParty2016.swf',
          town: 'archives:RoomsTown-HolidayParty2016.swf',
          cave: 'archives:RoomsCave-HolidayParty2016.swf'
        },
        music: {
          lounge: 1075,
          beacon: 583,
          boiler: 667,
          shop: 1086,
          cloudforest: 363,
          coffee: 1070,
          cove: 1071,
          shipquarters: 1083,
          shipnest: 1082,
          dock: 1152,
          dojo: 403,
          dojoext: 404,
          agentlobbymulti: 922,
          dojofire: 405,
          forest: 1088,
          lake: 666,
          rink: 592,
          berg: 1069,
          light: 1154,
          attic: 884,
          mall: 1076,
          ship: 1082,
          mine: 675,
          shack: 1090,
          dance: 1087,
          pet: 659,
          pizza: 1081,
          hotelroof: 360,
          hotelspa: 361,
          park: 658,
          pufflewild: 897,
          party13: 1091,
          school: 1085,
          shiphold: 1083,
          skatepark: 754,
          mtn: 1077,
          lodge: 1074,
          village: 1077,
          dojosnow: 407,
          forts: 1073,
          town: 1084,
          cave: 1153
        },
        localChanges: {
          'close_ups/cfc_interface.swf': { en: 'archives:ENClose_upsCfc_interface-HolidayParty2016.swf' },
          'close_ups/quest_interface.swf': { en: 'archives:Close_upsQuest_interface-HolidayParty2016.swf' }
        },
        globalChanges: {
          'membership/party1.swf': 'archives:MembershipParty1-HolidayParty2016.swf',
          'membership/party2.swf': 'archives:MembershipParty2-HolidayParty2016.swf',
          'membership/party3.swf': 'archives:MembershipParty3-HolidayParty2016.swf',
          'content/interface.swf': 'archives:ContentInterface-HolidayParty2016.swf',
          'content/party_icon.swf': 'archives:ContentParty_icon-HolidayParty2016.swf',
          'close_ups/character_dialogue_login.swf': 'archives:Close_ups161130_character_dialogue_login-HolidayParty2016.swf',
          'close_ups/161226_character_dialogue_congrats_final.swf': 'archives:Close_ups161226_character_dialogue_congrats_final-HolidayParty2016.swf',
          'close_ups/item_calendar.swf': 'archives:Close_upsItem_calendar_web-HolidayParty2016.swf',
          'close_ups/161130_transform_info.swf': 'archives:Close_ups161130_transform_info-HolidayParty2016.swf',
          'content/features.swf': 'archives:ContentFeatures-HolidayParty2016.swf',
          'content/logo.swf': 'archives:ContentLogo-HolidayParty2016.swf',
          'content/party.swf': 'archives:ContentParty-HolidayParty2016.swf',
          'content/prompts.swf': 'archives:ContentPrompts-HolidayParty2016.swf',
          'telescope/telescope.swf': 'archives:Telescope-HolidayParty2015.swf',
          'binoculars/binoculars.swf': 'archives:Binoculars-HolidayParty2015.swf'
        },
        fileChanges: {
          'play/v2/content/global/penguin/penguin_frostbite.swf': 'archives:PlayV2ContentGlobalPenguinPenguin_frostbite.swf',
          'play/v2/content/global/rooms/effects/avatar.swf': 'archives:RoomsEffectsAvatar-HolidayParty2015.swf'
        },
        coinsForChange: true
      }
    }
  }
];
