import { Update } from ".";

export const UPDATES_2015_PARTIES: Update[] = [
  {
    date: '2015-01-22',
    temp: {
      party: {
        partyName: 'Star Wars Rebels Takeover',
        partyIcon: 'party',
        rooms: {
          beach: 'archives:RoomsBeach-StarWarsRebelsTakeover.swf',
          cove: 'archives:RoomsCove-StarWarsRebelsTakeover.swf',
          dock: 'archives:RoomsDock-StarWarsRebelsTakeover.swf',
          forest: 'archives:RoomsForest-StarWarsRebelsTakeover.swf',
          plaza: 'archives:RoomsPlaza-StarWarsRebelsTakeover.swf',
          forts: 'archives:RoomsForts-StarWarsRebelsTakeover.swf',
          town: 'archives:RoomsTown-StarWarsRebelsTakeover.swf',
          party1: 'archives:RoomsParty1-StarWarsRebelsTakeover.swf',
          partysolo1: 'archives:RoomsPartysolo1-StarWarsRebelsTakeover.swf',
          party2: 'archives:RoomsParty2-StarWarsRebelsTakeover.swf'
        },
        music: {
          beach: 839,
          cove: 831,
          dock: 832,
          forest: 833,
          plaza: 835,
          forts: 834,
          town: 836,
          party1: 837,
          partysolo1: 838
        },
        map: 'archives:ContentMap-StarWarsRebelsTakeover.swf',
        startscreens: [ 'archives:LoginScreen-ENStarWarsRebelsTakeover-star-wars-rebels-pp.swf' ],
        localChanges: {
          'close_ups/quest_interface.swf': { en: 'archives:ENClose_upsQuest_interface-StarWarsRebelsTakeover.swf' }
        },
        globalChanges: {
          'membership/party1.swf': 'archives:MembershipParty1-StarWarsRebelsTakeover.swf',
          'content/party_icon.swf': 'archives:ContentParty_icon-StarWarsRebelsTakeover.swf',
          'close_ups/character_dialogue_instruction.swf': 'archives:Close_upsCharacter_dialogue_instruction-StarWarsRebelsTakeover.swf',
          'close_ups/character_dialogue_login.swf': 'archives:Close_upsCharacter_dialogue_login-StarWarsRebelsTakeover.swf',
          'close_ups/character_dialogue_task2complete.swf': 'archives:Close_upsCharacter_dialogue_task2complete-StarWarsRebelsTakeover.swf',
          'close_ups/character_dialogue_task4complete.swf': 'archives:Close_upsCharacter_dialogue_task4complete-StarWarsRebelsTakeover.swf',
          'close_ups/character_dialogue_task5.swf': 'archives:Close_upsCharacter_dialogue_task5-StarWarsRebelsTakeover.swf',
          'close_ups/character_dialogue_task5_collect.swf': 'archives:Close_upsCharacter_dialogue_task5_collect-StarWarsRebelsTakeover.swf',
          'close_ups/character_dialogue_task5complete.swf': 'archives:Close_upsCharacter_dialogue_task5complete-StarWarsRebelsTakeover.swf',
          'close_ups/character_dialogue_task6.swf': 'archives:Close_upsCharacter_dialogue_task6-StarWarsRebelsTakeover.swf',
          'close_ups/character_dialogue_task6a.swf': 'archives:Close_upsCharacter_dialogue_task6a-StarWarsRebelsTakeover.swf',
          'content/logo.swf': 'archives:ContentLogo-StarWarsRebelsTakeover.swf',
          'telescope/telescope.swf': 'archives:StarWarsRebelsTakeoverTelescopeEmpty2.swf'
        },
        fileChanges: {
          'play/v2/content/global/avatar/sprites/jedidual.swf': 'archives:AvatarSpritesJediDual.swf',
          'play/v2/content/global/avatar/sprites/jediinquisitor.swf': 'archives:AvatarSpritesJediInquisitor.swf',
          'play/v2/content/global/avatar/sprites/jedisingle.swf': 'archives:AvatarSpritesJediSingle.swf',
          'play/v2/content/global/avatar/sprites/inquisitor.swf': 'archives:AvatarSpritesInquisitor.swf'
        }
      }
    }
  },
  { date: '2015-02-05', end: [ 'party' ] },
  {
    date: '2015-02-19',
    temp: {
      party: {
        partyName: 'SoundStudio Party',
        partyIcon: 'party',
        rooms: {
          forts: 'archives:RoomsForts-SoundStudioParty2015.swf',
          coffee: 'archives:RoomsCoffee-SoundStudioParty2015.swf',
          dock: 'archives:RoomsDock-SoundStudioParty2015.swf',
          forest: 'archives:RoomsForest-SoundStudioParty2015.swf',
          plaza: 'archives:RoomsPlaza-SoundStudioParty2015.swf',
          rink: 'archives:RoomsRink-SoundStudioParty2015.swf',
          mall: 'archives:RoomsStage-SoundStudioParty2015.swf',
          town: 'archives:RoomsTown-SoundStudioParty2015.swf',
          party1: 'archives:RoomsParty1-SoundStudioParty2015.swf',
          party2: 'archives:RoomsParty2-SoundStudioParty2015.swf',
          party3: 'archives:RoomsParty3-SoundStudioParty2015.swf',
          party4: 'archives:RoomsParty4-SoundStudioParty2015.swf',
          party5: 'archives:RoomsParty5-SoundStudioParty2015.swf',
          partysolo1: 'archives:RoomsPartysolo1-SoundStudioParty2015.swf',
          partysolo2: 'archives:RoomsPartysolo2-SoundStudioParty2015.swf',
          partysolo3: 'archives:RoomsPartysolo3-SoundStudioParty2015.swf',
          partysolo4: 'archives:RoomsPartysolo4-SoundStudioParty2015.swf'
        },
        music: {
          coffee: 868,
          dock: 866,
          forest: 871,
          plaza: 870,
          forts: 869,
          rink: 865,
          mall: 872,
          town: 867,
          party1: 861,
          party2: 862,
          party3: 863,
          party4: 864,
          party5: 356,
          partysolo1: 873,
          partysolo2: 873,
          partysolo3: 873,
          partysolo4: 873
        },
        map: 'archives:ContentMap-SoundStudioParty.swf',
        localChanges: {
          'close_ups/quest_interface.swf': { en: 'archives:ENClose_upsQuest_interface-SoundStudioParty.swf' },
          'close_ups/cpidol_choose_closeup.swf': { en: 'archives:ENClose_upsCpidol_choose_closeup-SoundStudioParty2015.swf' },
          'close_ups/snowballrecords_choose_closeup.swf': { en: 'archives:ENClose_upsSnowballrecords_choose_closeup-SoundStudioParty2015.swf' }
        },
        globalChanges: {
          'membership/party1.swf': 'archives:MembershipParty1-SoundStudioParty2015.swf',
          'close_ups/character_dialogue_login.swf': 'archives:Close_upsCharacter_dialogue_login-SoundStudioParty.swf',
          'close_ups/item_rewards.swf': 'archives:Close_upsItem_rewards-SoundStudioParty2015.swf',
          'content/logo.swf': 'archives:ContentLogo-SoundStudioParty.swf'
        }
      }
    }
  },
  { date: '2015-03-04', end: [ 'party' ] },
  {
    date: '2015-03-26',
    temp: {
      party: {
        partyName: 'Puffle Party 2015',
        partyIcon: 'party',
        rooms: {
          lodge: 'archives:RoomsLodge-PuffleParty2015.swf',
          village: 'archives:RoomsVillage-PuffleParty2015.swf',
          beach: 'archives:RoomsBeach-PuffleParty2015.swf',
          shop: 'archives:RoomsShop-PuffleParty2015.swf',
          coffee: 'archives:RoomsCoffee-PuffleParty2015.swf',
          cove: 'archives:RoomsCove-PuffleParty2015.swf',
          dock: 'archives:RoomsDock-PuffleParty2015.swf',
          forest: 'archives:RoomsForest-PuffleParty2015.swf',
          light: 'archives:RoomsLight-PuffleParty2015.swf',
          party1: 'archives:RoomsParty1-PuffleParty2015.swf',
          party2: 'archives:RoomsParty2-PuffleParty2015.swf',
          party3: 'archives:RoomsParty3-PuffleParty2015.swf',
          plaza: 'archives:RoomsPlaza-PuffleParty2015.swf',
          forts: 'archives:RoomsForts-PuffleParty2015.swf',
          rink: 'archives:RoomsRink-PuffleParty2015.swf',
          mall: 'archives:RoomsStage-PuffleParty2015.swf',
          pufflewild: 'archives:RoomsPufflewild-PuffleParty2015.swf',
          town: 'archives:RoomsTown-PuffleParty2015.swf'
        },
        music: {
          village: 591,
          beach: 651,
          shop: 885,
          coffee: 886,
          cove: 653,
          dock: 888,
          forest: 665,
          light: 657,
          party1: 889,
          party2: 890,
          party3: 891,
          plaza: 893,
          lodge: 589,
          forts: 656,
          rink: 661,
          mall: 895,
          pufflewild: 894,
          town: 896
        },
        globalChanges: {
          'membership/party1.swf': 'archives:MembershipParty1-PuffleParty2015.swf',
          'content/party_icon.swf': 'archives:ContentParty_icon-PuffleParty2015.swf',
          'close_ups/character_dialogue_leadup.swf': 'archives:Close_upsCharacter_dialogue_leadup-PuffleParty2015.swf',
          'close_ups/character_dialogue_login.swf': 'archives:Close_upsCharacter_dialogue_login-PuffleParty2015.swf',
          'close_ups/character_dialogue_sasquash.swf': 'archives:Close_upsCharacter_dialogue_sasquash-PuffleParty2015.swf',
          'close_ups/character_dialogue_reaction.swf': 'archives:Close_upsCharacter_dialogue_reaction-PuffleParty2015.swf',
          'close_ups/character_dialogue_reaction2.swf': 'archives:Close_upsCharacter_dialogue_reaction2-PuffleParty2015.swf',
          'close_ups/character_dialogue_collect.swf': 'archives:Close_upsCharacter_dialogue_collect-PuffleParty2015.swf',
          'close_ups/character_dialogue_gary_coffee.swf': 'archives:Close_upsCharacter_dialogue_gary_coffee-PuffleParty2015.swf',
          'close_ups/character_dialogue_rockhopper_cheese.swf': 'archives:Close_upsCharacter_dialogue_rockhopper_cheese-PuffleParty2015.swf',
          'close_ups/character_dialogue_rookie_sandwich.swf': 'archives:Close_upsCharacter_dialogue_rookie_sandwich-PuffleParty2015.swf',
          'close_ups/item_rewards.swf': 'archives:Close_upsItem_rewards-PuffleParty2015.swf',
          'close_ups/march_comic.swf': 'archives:Close_upsMarch_comic-PuffleParty2015.swf',
          'close_ups/choose_puffle_color_deer.swf': 'archives:Close_upsChoose_puffle_color_deer-PuffleParty2015.swf',
          'close_ups/choose_puffle_color_rabbit.swf': 'archives:Close_upsChoose_puffle_color_rabbit-PuffleParty2015.swf',
          'close_ups/choose_puffle_color_raccoon.swf': 'archives:Close_upsChoose_puffle_color_raccoon-PuffleParty2015.swf',
          'content/logologo.swf': 'archives:ContentLogoLogo-PuffleParty2015.swf'
        },
        fileChanges: { 'play/v2/client/interface.swf': 'archives:ClientInterface-PuffleParty2015.swf' }
      }
    }
  },
  { date: '2015-04-09', end: [ 'party' ] },
  {
    date: '2015-04-15',
    temp: {
      party: {
        partyName: 'Cave Maze',
        partyIcon: 'party',
        rooms: {
          dock: 'archives:RoomsDock-CaveMaze.swf',
          party1: 'archives:RoomsParty1-CaveMaze.swf',
          party2: 'archives:RoomsParty2-CaveMaze.swf',
          party3: 'archives:RoomsParty3-CaveMaze.swf',
          party4: 'archives:RoomsParty4-CaveMaze.swf',
          party5: 'archives:RoomsParty5-CaveMaze.swf',
          party6: 'archives:RoomsParty6-CaveMaze.swf',
          party7: 'archives:RoomsParty7-CaveMaze.swf',
          party8: 'archives:RoomsParty8-CaveMaze.swf',
          party9: 'archives:RoomsParty9-CaveMaze.swf',
          party10: 'archives:RoomsParty10-CaveMaze.swf',
          party11: 'archives:RoomsParty11-CaveMaze.swf',
          party12: 'archives:RoomsParty12-CaveMaze.swf',
          plaza: 'archives:RoomsPlaza-CaveMaze.swf',
          forts: 'archives:RoomsForts-CaveMaze.swf',
          town: 'archives:RoomsTown-CaveMaze.swf'
        },
        music: {
          dock: 898,
          party1: 899,
          party2: 899,
          party3: 899,
          party4: 899,
          party5: 899,
          party6: 899,
          party7: 899,
          party8: 899,
          party9: 899,
          party10: 899,
          party11: 900,
          party12: 901,
          plaza: 677,
          forts: 587,
          town: 581
        },
        globalChanges: { 'close_ups/maze_map.swf': 'archives:Close_upsRUMaze_Map-CaveMaze.swf' }
      }
    }
  },
  {
    date: '2015-04-22',
    end: [ 'party' ],
    temp: {
      party2: {
        partyName: 'Frozen Fever Party',
        partyIcon: 'party',
        rooms: {
          beach: 'archives:RoomsBeach-FrozenFeverParty.swf',
          cove: 'archives:RoomsCove-FrozenFeverParty.swf',
          dock: 'archives:RoomsDock-FrozenFeverParty.swf',
          forest: 'archives:RoomsForest-FrozenFeverParty.swf',
          party1: 'archives:RoomsParty1-FrozenFeverParty.swf',
          party2: 'archives:RoomsParty2-FrozenFeverParty.swf',
          plaza: 'archives:RoomsPlaza-FrozenFeverParty.swf',
          forts: 'archives:RoomsForts-FrozenFeverParty.swf',
          town: 'archives:RoomsTown-FrozenFeverParty.swf',
          partysolo1: 'archives:RoomsConcertElsaconcert-FrozenFeverParty.swf'
        },
        music: {
          beach: 906,
          cove: 909,
          dock: 911,
          forest: 908,
          party1: 739,
          party2: 911,
          plaza: 910,
          forts: 909,
          town: 910,
          partysolo1: 739
        },
        map: 'archives:ContentMap-FrozenFeverParty.swf',
        localChanges: {
          'close_ups/quest_interface.swf': { en: 'archives:ENCloseUpsQuestInterface-FrozenFeverParty.swf' }
        },
        globalChanges: {
          'membership/party1.swf': 'archives:MembershipParty1-FrozenFeverParty.swf',
          'content/party_icon.swf': 'archives:ContentParty_icon-FrozenFeverParty.swf',
          'close_ups/character_dialogue_elsa.swf': 'archives:Close_upsCharacter_dialogue_elsa-FrozenFeverParty.swf',
          'close_ups/character_dialogue_login.swf': 'archives:CloseUpsCharacterDialogueLogin-FrozenFeverParty.swf'
        },
        fileChanges: {
          'play/v2/client/interface.swf': 'archives:ClientInterfaceFrozenFever2015.swf',
          'play/v2/content/global/avatar/sprites/olaf.swf': 'archives:AvatarSpritesOlaf.swf',
          'play/v2/content/global/avatar/sprites/marshmallow.swf': 'archives:AvatarSpritesMarshmallow-FrozenFeverParty.swf'
        }
      }
    }
  },
  {
    date: '2015-05-21',
    end: [ 'party2' ],
    temp: {
      party: {
        partyName: 'The Fair 2015',
        partyIcon: 'party',
        rooms: {
          beach: 'archives:RoomsBeach-TheFair2015.swf',
          beacon: 'archives:RoomsBeacon-TheFair2015.swf',
          book: 'archives:RoomsBook-TheFair2015.swf',
          shop: 'archives:RoomsShop-TheFair2015.swf',
          cloudforest: 'archives:RoomsCloudforest-TheFair2015.swf',
          coffee: 'archives:RoomsCoffee-TheFair2015.swf',
          cove: 'archives:RoomsCove-TheFair2015.swf',
          dock: 'archives:RoomsDock-TheFair2015.swf',
          dojo: 'archives:RoomsDojo-TheFair2015.swf',
          dojoext: 'archives:RoomsDojoext-TheFair2015.swf',
          agent: 'archives:TheFair2014EverydayPhoningFacility.swf',
          dojofire: 'archives:RoomsDojofire-TheFair2015.swf',
          forest: 'archives:RoomsForest-TheFair2015.swf',
          hotellobby: 'archives:RoomsHotellobby-TheFair2015.swf',
          hotelroof: 'archives:RoomsHotelroof-TheFair2015.swf',
          hotelspa: 'archives:RoomsHotelspa-TheFair2015.swf',
          berg: 'archives:RoomsBerg-TheFair2015.swf',
          light: 'archives:RoomsLight-TheFair2015.swf',
          attic: 'archives:RoomsAttic-TheFair2015.swf',
          shack: 'archives:RoomsShack-TheFair2015.swf',
          pet: 'archives:RoomsPet-TheFair2015.swf',
          pizza: 'archives:RoomsPizza-TheFair2015.swf',
          plaza: 'archives:RoomsPlaza-TheFair2015Mall.swf',
          park: 'archives:RoomsPark-TheFair2015.swf',
          pufflewild: 'archives:RoomsPufflewild-TheFair2015.swf',
          school: 'archives:RoomsSchool-TheFair2015.swf',
          skatepark: 'archives:RoomsSkatepark-TheFair2015.swf',
          mtn: 'archives:RoomsMtn-TheFair2015.swf',
          lodge: 'archives:RoomsLodge-TheFair2015.swf',
          village: 'archives:RoomsVillage-TheFair2015.swf',
          dojosnow: 'archives:RoomsDojosnow-TheFair2015.swf',
          forts: 'archives:RoomsForts-TheFair2015.swf',
          rink: 'archives:RoomsRink-TheFair2015.swf',
          town: 'archives:RoomsTown-TheFair2015.swf',
          party10: 'archives:RoomsParty10-TheFair2015.swf',
          party7: 'archives:RoomsParty7-TheFair2015.swf',
          party6: 'archives:RoomsParty6-TheFair2015.swf',
          party2: 'archives:RoomsParty2-TheFair2015.swf',
          party9: 'archives:RoomsParty9-TheFair2015.swf',
          party12: 'archives:RoomsParty12-TheFair2015.swf',
          party11: 'archives:RoomsParty11-TheFair2015.swf',
          party1: 'archives:RoomsParty1-TheFair2015.swf',
          party4: 'archives:RoomsParty4-TheFair2015.swf',
          party5: 'archives:RoomsParty5-TheFair2015.swf',
          party3: 'archives:RoomsParty3-TheFair2015.swf',
          party8: 'archives:RoomsParty8-TheFair2015.swf'
        },
        music: {
          beach: 582,
          beacon: 583,
          book: 669,
          shop: 345,
          cloudforest: 363,
          coffee: 429,
          cove: 579,
          dock: 611,
          dojo: 403,
          dojoext: 404,
          agent: 7,
          dojofire: 405,
          forest: 586,
          hotellobby: 362,
          hotelroof: 360,
          hotelspa: 361,
          berg: 584,
          light: 588,
          attic: 672,
          shack: 580,
          pet: 659,
          pizza: 676,
          plaza: 677,
          park: 658,
          pufflewild: 897,
          school: 436,
          skatepark: 754,
          mtn: 590,
          lodge: 589,
          village: 591,
          dojosnow: 407,
          forts: 587,
          rink: 592,
          town: 581,
          party10: 610,
          party7: 607,
          party6: 606,
          party2: 602,
          party9: 609,
          party12: 918,
          party11: 917,
          party1: 601,
          party4: 604,
          party5: 605,
          party3: 603,
          party8: 608
        },
        mapNote: 'archives:ENCloseUpsPartyMapNote-TheFair2015.swf',
        localChanges: {
          'close_ups/quest_interface.swf': { en: 'archives:CloseUpsEN-QuestInterface-TheFair2015.swf' },
          'close_ups/party_map.swf': { en: 'archives:ENCloseUpsPartyMapNote-TheFair2015.swf' },
          'close_ups/igloo_prompt.swf': { en: 'archives:ENCloseUpsIglooPrompt-TheFair2015.swf' },
          'close_ups/party_igloo_list.swf': { en: 'archives:ENCloseUpsPartyIglooList-TheFair2015.swf' },
          'close_ups/ride_prompt.swf': { en: 'archives:ENCloseUpsRidePrompt-TheFair2015.swf' }
        },
        globalChanges: {
          'membership/party1.swf': 'archives:MembershipParty1-TheFair2015.swf',
          'membership/party2.swf': 'archives:MembershipParty2-TheFair2015.swf',
          'content/party_icon.swf': 'archives:ContentParty_icon-TheFair2015.swf',
          'close_ups/dialogrookiefirstdailyspinlogin.swf': 'archives:CloseUpsDialogRookieFirstdailyspinLogin-TheFair2015.swf',
          'close_ups/character_dialogue_rookie_login.swf': 'archives:CloseUps-DialogueRookieLogin-TheFair2015.swf',
          'content/logo.swf': 'archives:ContentLogo-TheFair2015.swf'
        },
        fileChanges: {
          'play/v2/client/interface.swf': 'archives:ClientInterfaceFair2015.swf',
          'play/v2/content/global/rooms/effects/boatfront.swf': 'archives:RoomsEffectsBoatfront-TheFair2015.swf',
          'play/v2/content/global/rooms/effects/boatback.swf': 'archives:RoomsEffectsBoatback-TheFair2015.swf',
          'play/v2/content/global/rooms/effects/pixelpenguin.swf': 'archives:RoomsEffectsPixelpenguin-TheFair2015.swf',
          'play/v2/content/global/avatar/sprites/crab.swf': 'archives:AvatarSpritesCrab.swf',
          'play/v2/content/global/avatar/sprites/dragon.swf': 'archives:AvatarSpritesDragon.swf',
          'play/v2/content/global/avatar/sprites/robotcgrey.swf': 'archives:AvatarSpritesRobotCGrey.swf',
          'play/v2/content/global/avatar/sprites/werewolf.swf': 'archives:AvatarSpritesWerewolf.swf'
        }
      },
      party3: { partyName: 'Rainbow Puffle Party', partyIcon: 'party', rooms: {} }
    }
  },
  { date: '2015-06-10', end: [ 'party' ] },
  { date: '2015-06-17', end: [ 'party3' ] },
  {
    date: '2015-06-30',
    temp: {
      party: {
        partyName: 'Festival of Snow',
        partyIcon: 'party',
        rooms: {
          beach: 'archives:RoomsBeach-FestivalofSnow2015.swf',
          cove: 'archives:RoomsCove-FestivalofSnow2015.swf',
          dock: 'archives:RoomsDock-FestivalofSnow2015.swf',
          forest: 'archives:RoomsForest-FestivalofSnow2015.swf',
          berg: 'archives:RoomsBerg-FestivalofSnow2015.swf',
          shack: 'archives:RoomsShack-FestivalofSnow2015.swf',
          plaza: 'archives:RoomsPlaza-FestivalofSnow2015.swf',
          mtn: 'archives:RoomsMtn-FestivalofSnow2015.swf',
          village: 'archives:RoomsVillage-FestivalofSnow2015.swf',
          forts: 'archives:RoomsForts-FestivalofSnow2015.swf',
          town: 'archives:RoomsTown-FestivalofSnow2015.swf'
        },
        music: {
          beach: 923,
          cove: 923,
          dock: 923,
          forest: 924,
          berg: 923,
          shack: 924,
          plaza: 924,
          mtn: 925,
          village: 925,
          forts: 924,
          town: 924
        },
        globalChanges: {
          'close_ups/pedestal_adewilsom.swf': 'archives:Close_upsPedestal_adewilsom-FestivalofSnow2015.swf',
          'close_ups/pedestal_alexisfrio.swf': 'archives:Close_upsPedestal_alexisfrio-FestivalofSnow2015.swf',
          'close_ups/pedestal_barby015.swf': 'archives:Close_upsPedestal_barby015-FestivalofSnow2015.swf',
          'close_ups/pedestal_bridgey27.swf': 'archives:Close_upsPedestal_bridgey27-FestivalofSnow2015.swf',
          'close_ups/pedestal_bristevo.swf': 'archives:Close_upsPedestal_bristevo-FestivalofSnow2015.swf',
          'close_ups/pedestal_bubblz126.swf': 'archives:Close_upsPedestal_bubblz126-FestivalofSnow2015.swf',
          'close_ups/pedestal_chilly0ne.swf': 'archives:Close_upsPedestal_chilly0ne-FestivalofSnow2015.swf',
          'close_ups/pedestal_coco12277.swf': 'archives:Close_upsPedestal_coco12277-FestivalofSnow2015.swf',
          'close_ups/pedestal_concordio100.swf': 'archives:Close_upsPedestal_concordio100-FestivalofSnow2015.swf',
          'close_ups/pedestal_didipengy.swf': 'archives:Close_upsPedestal_didipengy-FestivalofSnow2015.swf',
          'close_ups/pedestal_floresita248.swf': 'archives:Close_upsPedestal_floresita248-FestivalofSnow2015.swf',
          'close_ups/pedestal_janeti86704.swf': 'archives:Close_upsPedestal_janeti86704-FestivalofSnow2015.swf',
          'close_ups/pedestal_lili3390.swf': 'archives:Close_upsPedestal_lili3390-FestivalofSnow2015.swf',
          'close_ups/pedestal_mepauset.swf': 'archives:Close_upsPedestal_mepauset-FestivalofSnow2015.swf',
          'close_ups/pedestal_nellora.swf': 'archives:Close_upsPedestal_nellora-FestivalofSnow2015.swf',
          'close_ups/pedestal_onelia1234.swf': 'archives:Close_upsPedestal_onelia1234-FestivalofSnow2015.swf',
          'close_ups/pedestal_opal2004.swf': 'archives:Close_upsPedestal_opal2004-FestivalofSnow2015.swf',
          'close_ups/pedestal_oscar4570.swf': 'archives:Close_upsPedestal_oscar4570-FestivalofSnow2015.swf',
          'close_ups/pedestal_patraquim1.swf': 'archives:Close_upsPedestal_patraquim1-FestivalofSnow2015.swf',
          'close_ups/pedestal_penny2415.swf': 'archives:Close_upsPedestal_penny2415-FestivalofSnow2015.swf',
          'close_ups/pedestal_pinguinchen.swf': 'archives:Close_upsPedestal_pinguinchen-FestivalofSnow2015.swf',
          'close_ups/pedestal_purble2553.swf': 'archives:Close_upsPedestal_purble2553-FestivalofSnow2015.swf',
          'close_ups/pedestal_rightangle.swf': 'archives:Close_upsPedestal_rightangle-FestivalofSnow2015.swf',
          'close_ups/pedestal_sahifira.swf': 'archives:Close_upsPedestal_sahifira-FestivalofSnow2015.swf',
          'close_ups/pedestal_shivie.swf': 'archives:Close_upsPedestal_shivie-FestivalofSnow2015.swf',
          'close_ups/pedestal_toon161.swf': 'archives:Close_upsPedestal_toon161-FestivalofSnow2015.swf',
          'close_ups/pedestal_tsveten1.swf': 'archives:Close_upsPedestal_tsveten1-FestivalofSnow2015.swf',
          'close_ups/pedestal_waddles5626.swf': 'archives:Close_upsPedestal_waddles5626-FestivalofSnow2015.swf',
          'close_ups/pedestal_largepedestal_large.swf': 'archives:Close_upsPedestal_largePedestal_large-FestivalofSnow2015.swf',
          'close_ups/morefanart_1.swf': 'archives:Close_upsMoreFanArt_1-FestivalofSnow2015.swf',
          'close_ups/morefanart_2.swf': 'archives:Close_upsMoreFanArt_2-FestivalofSnow2015.swf',
          'close_ups/morefanart_3.swf': 'archives:Close_upsMoreFanArt_3-FestivalofSnow2015.swf',
          'close_ups/morefanart_4.swf': 'archives:Close_upsMoreFanArt_4-FestivalofSnow2015.swf',
          'close_ups/morefanart_5.swf': 'archives:Close_upsMoreFanArt_5-FestivalofSnow2015.swf',
          'close_ups/morefanart_6.swf': 'archives:Close_upsMoreFanArt_6-FestivalofSnow2015.swf',
          'close_ups/morefanart_7.swf': 'archives:Close_upsMoreFanArt_7-FestivalofSnow2015.swf',
          'close_ups/morefanart_8.swf': 'archives:Close_upsMoreFanArt_8-FestivalofSnow2015.swf',
          'close_ups/morefanart_9.swf': 'archives:Close_upsMoreFanArt_9-FestivalofSnow2015.swf',
          'close_ups/morefanart_10.swf': 'archives:Close_upsMoreFanArt_10-FestivalofSnow2015.swf',
          'close_ups/morefanart_11.swf': 'archives:Close_upsMoreFanArt_11-FestivalofSnow2015.swf',
          'close_ups/morefanart_12.swf': 'archives:Close_upsMoreFanArt_12-FestivalofSnow2015.swf',
          'close_ups/morefanart_13.swf': 'archives:Close_upsMoreFanArt_13-FestivalofSnow2015.swf',
          'close_ups/morefanart_14.swf': 'archives:Close_upsMoreFanArt_14-FestivalofSnow2015.swf',
          'close_ups/morefanart_15.swf': 'archives:Close_upsMoreFanArt_15-FestivalofSnow2015.swf',
          'close_ups/morefanart_16.swf': 'archives:Close_upsMoreFanArt_16-FestivalofSnow2015.swf',
          'close_ups/morefanart_17.swf': 'archives:Close_upsMoreFanArt_17-FestivalofSnow2015.swf',
          'close_ups/morefanart_18.swf': 'archives:Close_upsMoreFanArt_18-FestivalofSnow2015.swf',
          'close_ups/morefanart_19.swf': 'archives:Close_upsMoreFanArt_19-FestivalofSnow2015.swf',
          'close_ups/morefanart_20.swf': 'archives:Close_upsMoreFanArt_20-FestivalofSnow2015.swf',
          'close_ups/morefanart_21.swf': 'archives:Close_upsMoreFanArt_21-FestivalofSnow2015.swf',
          'close_ups/morefanart_22.swf': 'archives:Close_upsMoreFanArt_22-FestivalofSnow2015.swf',
          'close_ups/morefanart_23.swf': 'archives:Close_upsMoreFanArt_23-FestivalofSnow2015.swf',
          'close_ups/morefanart_24.swf': 'archives:Close_upsMoreFanArt_24-FestivalofSnow2015.swf',
          'close_ups/morefanart_25.swf': 'archives:Close_upsMoreFanArt_25-FestivalofSnow2015.swf',
          'close_ups/morefanart_26.swf': 'archives:Close_upsMoreFanArt_26-FestivalofSnow2015.swf',
          'close_ups/morefanart_27.swf': 'archives:Close_upsMoreFanArt_27-FestivalofSnow2015.swf',
          'close_ups/morefanart_28.swf': 'archives:Close_upsMoreFanArt_28-FestivalofSnow2015.swf',
          'close_ups/morefanart_29.swf': 'archives:Close_upsMoreFanArt_29-FestivalofSnow2015.swf',
          'close_ups/morefanart_30.swf': 'archives:Close_upsMoreFanArt_30-FestivalofSnow2015.swf',
          'close_ups/morefanart_31.swf': 'archives:Close_upsMoreFanArt_31-FestivalofSnow2015.swf',
          'close_ups/morefanart_32.swf': 'archives:Close_upsMoreFanArt_32-FestivalofSnow2015.swf',
          'close_ups/morefanart_33.swf': 'archives:Close_upsMoreFanArt_33-FestivalofSnow2015.swf',
          'close_ups/morefanart_34.swf': 'archives:Close_upsMoreFanArt_34-FestivalofSnow2015.swf',
          'close_ups/morefanart_35.swf': 'archives:Close_upsMoreFanArt_35-FestivalofSnow2015.swf',
          'close_ups/morefanart_36.swf': 'archives:Close_upsMoreFanArt_36-FestivalofSnow2015.swf',
          'close_ups/morefanart_37.swf': 'archives:Close_upsMoreFanArt_37-FestivalofSnow2015.swf',
          'close_ups/morefanart_38.swf': 'archives:Close_upsMoreFanArt_38-FestivalofSnow2015.swf',
          'close_ups/morefanart_39.swf': 'archives:Close_upsMoreFanArt_39-FestivalofSnow2015.swf',
          'close_ups/morefanart_40.swf': 'archives:Close_upsMoreFanArt_40-FestivalofSnow2015.swf',
          'close_ups/morefanart_41.swf': 'archives:Close_upsMoreFanArt_41-FestivalofSnow2015.swf',
          'close_ups/morefanart_42.swf': 'archives:Close_upsMoreFanArt_42-FestivalofSnow2015.swf',
          'close_ups/morefanart_43.swf': 'archives:Close_upsMoreFanArt_43-FestivalofSnow2015.swf',
          'close_ups/morefanart_44.swf': 'archives:Close_upsMoreFanArt_44-FestivalofSnow2015.swf',
          'close_ups/morefanart_45.swf': 'archives:Close_upsMoreFanArt_45-FestivalofSnow2015.swf',
          'close_ups/morefanart_46.swf': 'archives:Close_upsMoreFanArt_46-FestivalofSnow2015.swf',
          'close_ups/morefanart_47.swf': 'archives:Close_upsMoreFanArt_47-FestivalofSnow2015.swf',
          'close_ups/morefanart_48.swf': 'archives:Close_upsMoreFanArt_48-FestivalofSnow2015.swf'
        }
      }
    }
  },
  { date: '2015-07-09', end: [ 'party' ] },
  {
    date: '2015-07-22',
    temp: {
      party: {
        partyName: 'Inside Out Party',
        partyIcon: 'party',
        rooms: {
          dock: 'archives:RoomsDock-InsideOutParty.swf',
          party1: 'archives:RoomsParty1-InsideOutParty.swf',
          party2: 'archives:RoomsParty2-InsideOutParty.swf',
          party3: 'archives:RoomsParty3-InsideOutParty.swf',
          party4: 'archives:RoomsParty4-InsideOutParty.swf',
          party5: 'archives:RoomsParty5-InsideOutParty.swf',
          party6: 'archives:RoomsParty6-InsideOutParty.swf'
        },
        music: { dock: 935, party1: 929, party2: 930, party3: 931, party4: 932, party5: 933, party6: 934 },
        localChanges: {
          'close_ups/quest_interface.swf': { en: 'archives:ENCloseUpsQuestInterface-InsideOutParty.swf' },
          'close_ups/mind_map.swf': { en: 'archives:ENCloseUpsMindMap-InsideOutParty.swf' }
        },
        globalChanges: {
          'membership/party1.swf': 'archives:MembershipParty1-InsideOutParty.swf',
          'content/party_icon.swf': 'archives:ContentParty_icon-InsideOutParty.swf',
          'close_ups/character_dialogue_leadup.swf': 'archives:Close_upsCharacter_dialogue_leadup-InsideOutPartyPre.swf',
          'close_ups/character_dialogue_login.swf': 'archives:Close_upsCharacter_dialogue_login-InsideOutParty.swf',
          'close_ups/character_dialogue_welcome.swf': 'archives:Close_upsCharacter_dialogue_welcome-InsideOutParty.swf',
          'close_ups/joy_dialogue_start.swf': 'archives:Close_upsJoy_dialogue_start-InsideOutParty.swf',
          'close_ups/joy_dialogue_collect.swf': 'archives:Close_upsJoy_dialogue_collect-InsideOutParty.swf',
          'close_ups/joy_dialogue_memory.swf': 'archives:Close_upsJoy_dialogue_memory-InsideOutParty.swf',
          'close_ups/joy_dialogue_complete.swf': 'archives:Close_upsJoy_dialogue_complete-InsideOutParty.swf',
          'close_ups/sadness_dialogue_start.swf': 'archives:Close_upsSadness_dialogue_start-InsideOutParty.swf',
          'close_ups/sadness_dialogue_collect.swf': 'archives:Close_upsSadness_dialogue_collect-InsideOutParty.swf',
          'close_ups/sadness_dialogue_memory.swf': 'archives:Close_upsSadness_dialogue_memory-InsideOutParty.swf',
          'close_ups/sadness_dialogue_complete.swf': 'archives:Close_upsSadness_dialogue_complete-InsideOutParty.swf',
          'close_ups/anger_dialogue_start.swf': 'archives:Close_upsAnger_dialogue_start-InsideOutParty.swf',
          'close_ups/anger_dialogue_collect.swf': 'archives:Close_upsAnger_dialogue_collect-InsideOutParty.swf',
          'close_ups/anger_dialogue_memory.swf': 'archives:Close_upsAnger_dialogue_memory-InsideOutParty.swf',
          'close_ups/anger_dialogue_complete.swf': 'archives:Close_upsAnger_dialogue_complete-InsideOutParty.swf',
          'close_ups/disgust_dialogue_start.swf': 'archives:Close_upsDisgust_dialogue_start-InsideOutParty.swf',
          'close_ups/disgust_dialogue_collect.swf': 'archives:Close_upsDisgust_dialogue_collect-InsideOutParty.swf',
          'close_ups/disgust_dialogue_memory.swf': 'archives:Close_upsDisgust_dialogue_memory-InsideOutParty.swf',
          'close_ups/disgust_dialogue_complete.swf': 'archives:Close_upsDisgust_dialogue_complete-InsideOutParty.swf',
          'close_ups/fear_dialogue_start.swf': 'archives:Close_upsFear_dialogue_start-InsideOutParty.swf',
          'close_ups/fear_dialogue_collect.swf': 'archives:Close_upsFear_dialogue_collect-InsideOutParty.swf',
          'close_ups/fear_dialogue_memory.swf': 'archives:Close_upsFear_dialogue_memory-InsideOutParty.swf',
          'close_ups/fear_dialogue_complete.swf': 'archives:Close_upsFear_dialogue_complete-InsideOutParty.swf',
          'close_ups/joy_dialogue_thanks.swf': 'archives:Close_upsJoy_dialogue_thanks-InsideOutParty.swf',
          'close_ups/character_dialogue_thanks_gary.swf': 'archives:Close_upsCharacter_dialogue_thanks_gary-InsideOutParty.swf',
          'close_ups/character_dialogue_thanks_rh.swf': 'archives:Close_upsCharacter_dialogue_thanks_rh-InsideOutParty.swf',
          'content/logo.swf': 'archives:ContentLogo-InsideOutParty.swf'
        },
        fileChanges: {
          'play/v2/client/interface.swf': 'archives:ClientInterface-InsideOutParty.swf',
          'play/v2/content/global/rooms/effects/avatar.swf': 'archives:RoomsEffectsAvatar-InsideOutParty.swf'
        }
      }
    }
  },
  { date: '2015-08-05', end: [ 'party' ] },
  {
    date: '2015-08-26',
    temp: {
      party: {
        partyName: 'Fashion Festival',
        partyIcon: 'party',
        rooms: {
          dock: 'archives:RoomsDock-FashionFestival.swf',
          party1: 'archives:RoomsParty1-FashionFestival.swf',
          forest: 'archives:RoomsForest-FashionFestival.swf',
          plaza: 'archives:RoomsPlaza-FashionFestival.swf',
          forts: 'archives:RoomsForts-FashionFestival.swf',
          rink: 'archives:RoomsRink-FashionFestival.swf',
          town: 'archives:RoomsTown-FashionFestival.swf',
          beach: 'archives:RoomsBeach-TheFair2015.swf',
          beacon: 'archives:RoomsBeacon-TheFair2015.swf',
          book: 'archives:RoomsBook-TheFair2015.swf',
          shop: 'archives:RoomsShop-FashionFestival.swf',
          cloudforest: 'archives:RoomsCloudforest-TheFair2015.swf',
          coffee: 'archives:RoomsCoffee-TheFair2015.swf',
          cove: 'archives:RoomsCove-TheFair2015.swf',
          dojo: 'archives:RoomsDojo-TheFair2015.swf',
          dojoext: 'archives:RoomsDojoext-TheFair2015.swf',
          agent: 'archives:TheFair2014EverydayPhoningFacility.swf',
          dojofire: 'archives:RoomsDojofire-TheFair2015.swf',
          berg: 'archives:RoomsBerg-TheFair2015.swf',
          light: 'archives:RoomsLight-TheFair2015.swf',
          attic: 'archives:RoomsAttic-TheFair2015.swf',
          shack: 'archives:RoomsShack-TheFair2015.swf',
          pet: 'archives:RoomsPet-TheFair2015.swf',
          pizza: 'archives:RoomsPizza-TheFair2015.swf',
          hotellobby: 'archives:RoomsHotellobby-TheFair2015.swf',
          hotelroof: 'archives:RoomsHotelroof-TheFair2015.swf',
          hotelspa: 'archives:RoomsHotelspa-TheFair2015.swf',
          park: 'archives:RoomsPark-TheFair2015.swf',
          pufflewild: 'archives:RoomsPufflewild-TheFair2015.swf',
          school: 'archives:RoomsSchool-TheFair2015.swf',
          skatepark: 'archives:RoomsSkatepark-TheFair2015.swf',
          mtn: 'archives:RoomsMtn-TheFair2015.swf',
          lodge: 'archives:RoomsLodge-TheFair2015.swf',
          village: 'archives:RoomsVillage-FashionFestival.swf',
          dojosnow: 'archives:RoomsDojosnow-TheFair2015.swf'
        },
        music: {
          dock: 946,
          party1: 948,
          forest: 945,
          plaza: 947,
          forts: 949,
          rink: 941,
          town: 947,
          beach: 582,
          beacon: 583,
          book: 669,
          shop: 943,
          cloudforest: 363,
          coffee: 944,
          cove: 579,
          dojo: 403,
          dojoext: 404,
          agent: 922,
          dojofire: 405,
          berg: 584,
          light: 588,
          attic: 884,
          shack: 580,
          pet: 659,
          pizza: 676,
          hotellobby: 362,
          hotelroof: 360,
          hotelspa: 361,
          park: 658,
          pufflewild: 897,
          school: 436,
          skatepark: 754,
          mtn: 590,
          lodge: 589,
          village: 591,
          dojosnow: 407
        },
        localChanges: {
          'close_ups/quest_interface.swf': { en: 'archives:Close_upsQuest_interface-FashionFestival.swf' }
        },
        globalChanges: {
          'close_ups/my_submissions_interface.swf': 'archives:Close_upsMy_submissions_interface-FashionFestival.swf',
          'close_ups/my_submissions_interface_fashionfestival_2.swf': 'archives:Close_upsMy_submissions_interface-FashionFestival_2.swf',
          'close_ups/voting_interface.swf': 'archives:Close_upsVoting_interface-FashionFestival.swf',
          'close_ups/voting_interface_fashionfestival_2.swf': 'archives:Close_upsVoting_interface-FashionFestival_2.swf',
          'content/party_icon.swf': 'archives:ContentParty_icon-FashionFestival.swf',
          'close_ups/character_dialogue_login.swf': 'archives:Close_upsCharacter_dialogue_login_winners-FashionFestival_2.swf',
          'close_ups/character_dialogue_submit.swf': 'archives:Close_upsCharacter_dialogue_submit-FashionFestival.swf',
          'close_ups/character_dialogue_submit_fashionfestival_2.swf': 'archives:Close_upsCharacter_dialogue_submit-FashionFestival_2.swf',
          'close_ups/submit_contest.swf': 'archives:Close_upsSubmit_contest-FashionFestival.swf',
          'close_ups/submitfail_duplicate.swf': 'archives:Close_upsSubmitfail_duplicate-FashionFestival.swf',
          'close_ups/submitfail_duplicate_fashionfestival_2.swf': 'archives:Close_upsSubmitfail_duplicate-FashionFestival_2.swf',
          'close_ups/submitfail_error.swf': 'archives:Close_upsSubmitfail_error-FashionFestival.swf',
          'close_ups/submitfail_noclothes.swf': 'archives:Close_upsSubmitfail_noclothes-FashionFestival.swf',
          'close_ups/submitfail_noclothes_fashionfestival_2.swf': 'archives:Close_upsSubmitfail_noclothes-FashionFestival_2.swf',
          'close_ups/submitfail_notickets.swf': 'archives:Close_upsSubmitfail_notickets-FashionFestival.swf',
          'content/logo.swf': 'archives:ContentLogo-FashionFestival.swf',
          'telescope/telescope.swf': 'archives:Telescope-FashionFestival.swf',
          'binoculars/binoculars.swf': 'archives:Binoculars-FashionFestival.swf'
        },
        fileChanges: { 'play/v2/client/interface.swf': 'archives:ClientInterface-FashionFestival_3.swf' }
      }
    }
  },
  {
    date: '2015-09-16',
    end: [ 'party' ],
    temp: {
      party2: {
        partyName: 'Descendants Party',
        partyIcon: 'party',
        rooms: {
          berg: 'archives:RoomsBerg-DescendantsParty.swf',
          shack: 'archives:RoomsShack-DescendantsParty.swf',
          school: 'archives:RoomsSchool-DescendantsParty.swf'
        },
        music: { berg: 954, shack: 955, school: 956 },
        localChanges: {
          'catalogues/interface.swf': { en: 'archives:Close_upsCatalog_interface-DescendantsParty.swf' }
        },
        globalChanges: {
          'content/party_icon.swf': 'archives:ContentParty_icon-DescendantsParty.swf',
          'close_ups/character_dialogue_login.swf': 'archives:Close_upsCharacter_dialogue_login-DescendantsParty.swf'
        },
        fileChanges: { 'play/v2/client/interface.swf': 'archives:ClientInterface-DescendantsParty.swf' }
      },
      party3: {
        partyName: 'Talk Like a Pirate Day',
        partyIcon: 'party',
        rooms: { beach: 'archives:RoomsBeach-TalkLikeAPirateDay.swf' },
        music: { beach: 957 }
      }
    }
  },
  { date: '2015-09-23', end: [ 'party3' ] },
  {
    date: '2015-09-30',
    end: [ 'party2' ],
    temp: {
      party: {
        partyName: '10th Anniversary Party',
        partyIcon: 'party',
        rooms: {
          beach: 'archives:10thAnniversaryPartyBeach.swf',
          beacon: 'archives:10thAnniversaryPartyBeacon.swf',
          book: 'archives:10thAnniversaryPartyBookRoom.swf',
          shop: 'archives:10thAnniversaryPartyClothesShop.swf',
          coffee: 'archives:10thAnniversaryPartyCoffeeShop.swf',
          cove: 'archives:10thAnniversaryPartyCove.swf',
          dance: 'archives:10thAnniversaryPartyDanceClub.swf',
          dock: 'archives:10thAnniversaryPartyDock.swf',
          forest: 'archives:10thAnniversaryPartyForest.swf',
          berg: 'archives:10thAnniversaryPartyIceberg.swf',
          light: 'archives:10thAnniversaryPartyLighthouse.swf',
          lounge: 'archives:10thAnniversaryPartyArcade.swf',
          shack: 'archives:10thAnniversaryPartyMineShack.swf',
          pizza: 'archives:10thAnniversaryPartyPizzaParlor.swf',
          plaza: 'archives:10thAnniversaryPartyPlaza.swf',
          mall: 'archives:10thAnniversaryPartyMall.swf',
          school: 'archives:10thAnniversaryPartySchool.swf',
          mtn: 'archives:10thAnniversaryPartySkiHill.swf',
          village: 'archives:10thAnniversaryPartySkiVillage.swf',
          forts: 'archives:10thAnniversaryPartySnowForts.swf',
          rink: 'archives:10thAnniversaryPartyIceRink.swf',
          town: 'archives:RoomsTown-10thAnniversaryParty.swf',
          party1: 'archives:10thAnniversaryPartyCasaFiesta.swf',
          party2: 'archives:10thAnniversaryPartyEpicWave.swf',
          party3: 'archives:10thAnniversaryPartyHighway.swf',
          party4: 'archives:10thAnniversaryPartySantasSled.swf',
          party5: 'archives:10thAnniversaryPartyPuffleFeedingArea.swf',
          party6: 'archives:10thAnniversaryPartySecretLaboratory.swf',
          party7: 'archives:10thAnniversaryPartyTreeForts.swf',
          party8: 'archives:10thAnniversaryPartyWizardLibrary.swf'
        },
        music: {
          beach: 1001,
          beacon: 1002,
          book: 1004,
          shop: 1026,
          coffee: 1029,
          cove: 1005,
          dance: 1006,
          dock: 1007,
          forest: 1008,
          berg: 1003,
          light: 1010,
          lounge: 1011,
          shack: 1025,
          pizza: 1021,
          plaza: 1022,
          mall: 1012,
          school: 1024,
          mtn: 1013,
          village: 1027,
          forts: 1009,
          rink: 1023,
          town: 1030
        },
        localChanges: {
          'catalogues/clothing.swf': { en: 'archives:MembershipCatalog_clothing-10thAnniversaryParty.swf' },
          'forms/library.swf': { en: 'archives:ENLibrarySep2015.swf' },
          'books/year1415.swf': { en: 'archives:ENBooksYear1415.swf' }
        },
        globalChanges: {
          'content/party_icon.swf': 'archives:ContentParty_icon-10thAnniversaryParty.swf',
          'close_ups/item_calendar.swf': 'archives:Close_ups_item_calendar-10thAnniversaryParty.swf',
          'close_ups/character_dialogue_login.swf': 'archives:Close_upsCharacter_dialogue_login-10thAnniversaryParty.swf',
          'close_ups/character_dialogue_real_auntarctic.swf': 'archives:Close_upsCharacter_dialogue_real_auntarctic-10thAnniversaryParty.swf',
          'close_ups/character_dialogue_auntarctic.swf': 'archives:Close_upsCharacter_dialogue_auntarctic-10thAnniversaryParty.swf',
          'close_ups/character_dialogue_auntarctic_10thanniversaryparty_2.swf': 'archives:Close_upsCharacter_dialogue_auntarctic-10thAnniversaryParty_2.swf',
          'close_ups/character_dialogue_cadence.swf': 'archives:Close_upsCharacter_dialogue_cadence-10thAnniversaryParty.swf',
          'close_ups/character_dialogue_cadence_10thanniversaryparty_2.swf': 'archives:Close_upsCharacter_dialogue_cadence-10thAnniversaryParty_2.swf',
          'close_ups/character_dialogue_dot.swf': 'archives:Close_upsCharacter_dialogue_dot-10thAnniversaryParty.swf',
          'close_ups/character_dialogue_dot_10thanniversaryparty_2.swf': 'archives:Close_upsCharacter_dialogue_dot-10thAnniversaryParty_2.swf',
          'close_ups/character_dialogue_gary.swf': 'archives:Close_upsCharacter_dialogue_gary-10thAnniversaryParty.swf',
          'close_ups/character_dialogue_gary_10thanniversaryparty_2.swf': 'archives:Close_upsCharacter_dialogue_gary-10thAnniversaryParty_2.swf',
          'close_ups/character_dialogue_npc.swf': 'archives:Close_upsCharacter_dialogue_npc-10thAnniversaryParty.swf',
          'close_ups/character_dialogue_ph.swf': 'archives:Close_upsCharacter_dialogue_ph-10thAnniversaryParty.swf',
          'close_ups/character_dialogue_ph_10thanniversaryparty_2.swf': 'archives:Close_upsCharacter_dialogue_ph-10thAnniversaryParty_2.swf',
          'close_ups/character_dialogue_rockhopper.swf': 'archives:Close_upsCharacter_dialogue_rockhopper-10thAnniversaryParty.swf',
          'close_ups/character_dialogue_rockhopper_10thanniversaryparty_2.swf': 'archives:Close_upsCharacter_dialogue_rockhopper-10thAnniversaryParty_2.swf',
          'close_ups/character_dialogue_rookie.swf': 'archives:Close_upsCharacter_dialogue_rookie-10thAnniversaryParty.swf',
          'close_ups/character_dialogue_rookie_10thanniversaryparty_2.swf': 'archives:Close_upsCharacter_dialogue_rookie-10thAnniversaryParty_2.swf',
          'close_ups/character_dialogue_sensei.swf': 'archives:Close_upsCharacter_dialogue_sensei-10thAnniversaryParty.swf',
          'close_ups/character_dialogue_sensei_10thanniversaryparty_2.swf': 'archives:Close_upsCharacter_dialogue_sensei-10thAnniversaryParty_2.swf',
          'content/logo.swf': 'archives:ContentLogo-10thAnniversaryParty.swf'
        },
        fileChanges: { 'play/v2/client/interface.swf': 'archives:ClientInterface-10thAnniversaryParty.swf' }
      }
    }
  },
  {
    date: '2015-10-21',
    end: [ 'party' ],
    temp: {
      party2: {
        partyName: 'Halloween Party 2015',
        partyIcon: 'party',
        rooms: {
          beach: 'archives:Hallo15_beach.swf',
          beacon: 'archives:Hallo15_beacon.swf',
          book: 'archives:Hallo15_book.swf',
          cave: 'archives:Hallo15_cave.swf',
          shop: 'archives:Hallo15_shop.swf',
          cloudforest: 'archives:Hallo15_cloudforest.swf',
          coffee: 'archives:Hallo15_coffee.swf',
          cove: 'archives:Hallo15_cove.swf',
          dance: 'archives:Hallo15_dance.swf',
          dock: 'archives:Hallo15_dock.swf',
          dojo: 'archives:Hallo15_dojo.swf',
          dojoext: 'archives:Hallo15_dojoext.swf',
          agentlobbymulti: 'archives:Hallo15_agentlobbymulti.swf',
          dojofire: 'archives:Hallo15_dojofire.swf',
          forest: 'archives:Hallo15_forest.swf',
          party1: 'archives:Hallo15_party1.swf',
          party2: 'archives:Hallo15_party2.swf',
          berg: 'archives:Hallo15_berg.swf',
          light: 'archives:Hallo15_light.swf',
          attic: 'archives:Hallo15_attic.swf',
          lounge: 'archives:Hallo15_lounge.swf',
          shack: 'archives:Hallo15_shack.swf',
          pet: 'archives:Hallo15_pet.swf',
          pizza: 'archives:Hallo15_pizza.swf',
          plaza: 'archives:Hallo15_plaza.swf',
          mall: 'archives:Hallo15_mall.swf',
          hotellobby: 'archives:Hallo15_hotellobby.swf',
          hotelroof: 'archives:Hallo15_hotelroof.swf',
          hotelspa: 'archives:Hallo15_hotelspa.swf',
          park: 'archives:Hallo15_park.swf',
          pufflewild: 'archives:Hallo15_pufflewild.swf',
          school: 'archives:Hallo15_school.swf',
          skatepark: 'archives:Hallo15_skatepark.swf',
          mtn: 'archives:Hallo15_mtn.swf',
          lodge: 'archives:Hallo15_lodge.swf',
          village: 'archives:Hallo15_village.swf',
          dojosnow: 'archives:Hallo15_dojosnow.swf',
          forts: 'archives:Hallo15_forts.swf',
          rink: 'archives:Hallo15_rink.swf',
          town: 'archives:RoomsTown-HalloweenParty2015.swf'
        },
        music: {
          beach: 1054,
          beacon: 1053,
          book: 669,
          cave: 532,
          shop: 345,
          cloudforest: 1044,
          coffee: 1031,
          cove: 1035,
          dance: 1036,
          dock: 1037,
          dojo: 403,
          dojoext: 1045,
          agentlobbymulti: 922,
          dojofire: 1046,
          forest: 1038,
          party1: 838,
          party2: 1058,
          berg: 1043,
          light: 588,
          attic: 884,
          lounge: 1055,
          shack: 1041,
          pet: 659,
          pizza: 1033,
          plaza: 1052,
          mall: 1032,
          hotellobby: 1048,
          hotelroof: 1049,
          hotelspa: 1050,
          park: 1051,
          pufflewild: 1057,
          school: 1040,
          skatepark: 1034,
          mtn: 1042,
          lodge: 1056,
          village: 1042,
          dojosnow: 1047,
          forts: 1039,
          rink: 1067,
          town: 1052
        },
        localChanges: {
          'close_ups/quest_interface.swf': { en: 'archives:Close_upsQuest_interface-HalloweenParty2015.swf' }
        },
        globalChanges: {
          'membership/party1.swf': 'archives:MembershipParty1-HalloweenParty2015.swf',
          'membership/party2.swf': 'archives:MembershipParty2-HalloweenParty2015.swf',
          'content/party_icon.swf': 'archives:ContentParty_icon-HalloweenParty2015.swf',
          'close_ups/aa_start.swf': 'archives:Hallo15_dialogue_AA_start.swf',
          'close_ups/cad_start.swf': 'archives:Hallo15_dialogue_Cad_start.swf',
          'close_ups/dot_start.swf': 'archives:Hallo15_dialogue_Dot_start.swf',
          'close_ups/ph_start.swf': 'archives:Hallo15_dialogue_PH_start.swf',
          'close_ups/rh_start.swf': 'archives:Hallo15_dialogue_RH_start.swf',
          'close_ups/rook_start.swf': 'archives:Hallo15_dialogue_Rook_start.swf',
          'close_ups/sen_start.swf': 'archives:Hallo15_dialogue_Sen_start.swf',
          'close_ups/tiles_minigame0.swf': 'archives:Close_upsTiles_minigame0-HalloweenParty2015.swf',
          'close_ups/tiles_minigame1.swf': 'archives:Close_upsTiles_minigame1-HalloweenParty2015.swf',
          'close_ups/tiles_minigame2.swf': 'archives:Close_upsTiles_minigame2-HalloweenParty2015.swf',
          'close_ups/tiles_minigame3.swf': 'archives:Close_upsTiles_minigame3-HalloweenParty2015.swf',
          'close_ups/tiles_minigame4.swf': 'archives:Close_upsTiles_minigame4-HalloweenParty2015.swf',
          'close_ups/tiles_minigame5.swf': 'archives:Close_upsTiles_minigame5-HalloweenParty2015.swf',
          'close_ups/tiles_minigame6.swf': 'archives:Close_upsTiles_minigame6-HalloweenParty2015.swf',
          'close_ups/tiles_minigame7.swf': 'archives:Close_upsTiles_minigame7-HalloweenParty2015.swf',
          'close_ups/tiles_minigame8.swf': 'archives:Close_upsTiles_minigame8-HalloweenParty2015.swf',
          'content/features.swf': 'archives:ContentFeatures-HalloweenParty2015.swf',
          'content/logo.swf': 'archives:ContentLogo-HalloweenParty2015.swf',
          'close_ups/login.swf': 'archives:Hallo15_dialogue_login.swf',
          'close_ups/aa_instruct.swf': 'archives:Hallo15_dialogue_AA_instruct.swf',
          'close_ups/dot_instruct.swf': 'archives:Hallo15_dialogue_Dot_instruct.swf',
          'close_ups/rh_instruct.swf': 'archives:Hallo15_dialogue_RH_instruct.swf',
          'close_ups/rookie_bot.swf': 'archives:Hallo15_dialogue_Rookie_bot.swf',
          'close_ups/sen_instruct.swf': 'archives:Hallo15_dialogue_Sen_instruct.swf',
          'close_ups/gary_instruct.swf': 'archives:Hallo15_dialogue_Gary_instruct.swf',
          'close_ups/herbert_caged.swf': 'archives:Hallo15_dialogue_Herbert_caged.swf',
          'close_ups/herbert_monologue.swf': 'archives:Hallo15_dialogue_Herbert_monologue.swf',
          'telescope/telescope.swf': 'archives:Telescope-HalloweenParty2015.swf',
          'binoculars/binoculars.swf': 'archives:Binoculars-HalloweenParty2015.swf'
        },
        fileChanges: { 'play/v2/client/interface.swf': 'archives:ClientInterface-HalloweenParty2015.swf' }
      }
    }
  },
  {
    date: '2015-11-04',
    end: [ 'party2' ],
    temp: {
      party: {
        partyName: 'Mustache Madness',
        partyIcon: 'party',
        rooms: { forest: 'archives:RoomsForest-MustacheMadness.swf' },
        music: { forest: 1066 },
        globalChanges: {
          'close_ups/character_dialogue_mustache_login.swf': 'archives:Close_upsCharacter_dialogue_mustache_login-MustacheMadness.swf'
        }
      }
    }
  },
  {
    date: '2015-11-11',
    end: [ 'party' ],
    temp: {
      party2: {
        partyName: 'Extreme Paint Festival',
        partyIcon: 'party',
        rooms: { dock: 'archives:RoomsDock-ExtremePaintFestival.swf' },
        music: { dock: 1068 },
        globalChanges: {
          'close_ups/character_dialogue_november_leadup_login.swf': 'archives:Close_upsCharacter_dialogue_november_leadup_login-ExtremePaintFestival.swf'
        }
      }
    }
  },
  {
    date: '2015-11-18',
    temp: {
      party: {
        partyName: 'Operation: Crustacean',
        partyIcon: 'party',
        rooms: {
          dock: 'archives:RoomsDock-OperationCrustacean.swf',
          party1: 'archives:RoomsParty1-OperationCrustacean.swf',
          party6: 'archives:RoomsParty6-OperationCrustacean.swf',
          party7: 'archives:RoomsParty7-OperationCrustacean.swf',
          party5: 'archives:RoomsParty5-OperationCrustacean.swf',
          party8: 'archives:RoomsParty8-OperationCrustacean.swf',
          party9: 'archives:RoomsParty9-OperationCrustacean.swf',
          party10: 'archives:RoomsParty10-OperationCrustacean.swf',
          party11: 'archives:RoomsParty11-OperationCrustacean.swf',
          party3: 'archives:RoomsParty3-OperationCrustacean.swf',
          party12: 'archives:RoomsParty12-OperationCrustacean.swf'
        },
        music: {
          dock: 1060,
          party1: 1061,
          party6: 1064,
          party7: 1064,
          party5: 1064,
          party8: 1064,
          party9: 1064,
          party10: 1064,
          party11: 1064,
          party12: 1063
        },
        localChanges: {
          'close_ups/quest_interface.swf': { en: 'archives:Close_upsQuest_interface-OperationCrustacean.swf' }
        },
        globalChanges: {
          'membership/party1.swf': 'archives:MembershipParty1-OperationCrustacean.swf',
          'membership/party2.swf': 'archives:MembershipParty2-OperationCrustacean.swf',
          'content/party_icon.swf': 'archives:ContentParty_icon-OperationCrustacean.swf',
          'close_ups/character_dialogue_november_login.swf': 'archives:Close_upsCharacter_dialogue_november_login-OperationCrustacean.swf',
          'close_ups/character_dialogue_directions_jpg.swf': 'archives:Close_upsCharacter_dialogue_directions_JPG-OperationCrustacean.swf',
          'close_ups/character_dialogue_herbert_jpg_party1.swf': 'archives:Close_upsCharacter_dialogue_herbert_JPG_party1-OperationCrustacean.swf',
          'close_ups/character_dialogue_spacehub_herbert2.swf': 'archives:Close_upsCharacter_dialogue_spacehub_herbert2-OperationCrustacean.swf',
          'close_ups/character_dialogue_spacehub_herbert3.swf': 'archives:Close_upsCharacter_dialogue_spacehub_herbert3-OperationCrustacean.swf',
          'close_ups/character_dialogue_spacehub_herbert4.swf': 'archives:Close_upsCharacter_dialogue_spacehub_herbert4-OperationCrustacean.swf',
          'close_ups/character_dialogue_spacehub_jpg2.swf': 'archives:Close_upsCharacter_dialogue_spacehub_JPG2-OperationCrustacean.swf',
          'close_ups/character_dialogue_jpg_maze_entrance.swf': 'archives:Close_upsCharacter_dialogue_JPG_maze_entrance-OperationCrustacean.swf',
          'close_ups/character_dialogue_jpg_congrats_maze1.swf': 'archives:Close_upsCharacter_dialogue_JPG_congrats_maze1-OperationCrustacean.swf',
          'close_ups/character_dialogue_jpg_congrats_maze2.swf': 'archives:Close_upsCharacter_dialogue_JPG_congrats_maze2-OperationCrustacean.swf',
          'close_ups/character_dialogue_jpg_congrats_maze3.swf': 'archives:Close_upsCharacter_dialogue_JPG_congrats_maze3-OperationCrustacean.swf',
          'close_ups/character_dialogue_jpg_congrats_maze4.swf': 'archives:Close_upsCharacter_dialogue_JPG_congrats_maze4-OperationCrustacean.swf',
          'close_ups/character_dialogue_jpg_new_alert.swf': 'archives:Close_upsCharacter_dialogue_JPG_new_alert-OperationCrustacean.swf',
          'close_ups/character_dialogue_director_final_congrats.swf': 'archives:Close_upsCharacter_dialogue_director_final_congrats-OperationCrustacean.swf',
          'close_ups/choose_puffle_color_alien.swf': 'archives:Close_upsChoose_puffle_color_alien-OperationCrustacean.swf',
          'content/features.swf': 'archives:ContentFeatures-OperationCrustacean.swf',
          'content/logo.swf': 'archives:ContentLogo-OperationCrustacean.swf'
        },
        fileChanges: {
          'play/v2/client/interface.swf': 'archives:ClientInterface-OperationCrustacean.swf',
          'play/v2/client/party.swf': 'archives:ClientParty-OperationCrustacean.swf'
        }
      }
    }
  },
  { date: '2015-12-03', end: [ 'party' ] },
  {
    date: '2015-12-16',
    end: [ 'party2' ],
    temp: {
      party: {
        partyName: 'Holiday Party 2015',
        partyIcon: 'party',
        rooms: {
          forts: 'archives:RoomsForts-HolidayParty2015.swf',
          party1: 'archives:RoomsParty1-HolidayParty2015.swf',
          party14: 'archives:RoomsParty14-HolidayParty2015.swf',
          beach: 'archives:RoomsBeach-HolidayParty2015.swf',
          beacon: 'archives:RoomsBeacon-HolidayParty2015.swf',
          book: 'archives:RoomsBook-HolidayParty2015.swf',
          shipquarters: 'archives:RoomsShipquarters-HolidayParty2015.swf',
          shop: 'archives:RoomsShop-HolidayParty2015.swf',
          cloudforest: 'archives:RoomsCloudforest-HolidayParty2015.swf',
          coffee: 'archives:RoomsCoffee-HolidayParty2015.swf',
          cove: 'archives:RoomsCove-HolidayParty2015.swf',
          shipnest: 'archives:RoomsShipnest-HolidayParty2015.swf',
          dock: 'archives:RoomsDock-HolidayParty2015.swf',
          dojo: 'archives:RoomsDojo-HolidayParty2015.swf',
          dojoext: 'archives:RoomsDojoext-HolidayParty2015.swf',
          agentlobbymulti: 'archives:RoomsAgentlobbymulti-HolidayParty2015.swf',
          dojofire: 'archives:RoomsDojofire-HolidayParty2015.swf',
          forest: 'archives:RoomsForest-HolidayParty2015.swf',
          rink: 'archives:RoomsRink-HolidayParty2015.swf',
          berg: 'archives:RoomsBerg-HolidayParty2015.swf',
          light: 'archives:RoomsLight-HolidayParty2015.swf',
          attic: 'archives:RoomsAttic-HolidayParty2015.swf',
          lounge: 'archives:RoomsLounge-HolidayParty2015.swf',
          party13: 'archives:RoomsParty13-HolidayParty2015.swf',
          mall: 'archives:RoomsMall-HolidayParty2015.swf',
          shack: 'archives:RoomsShack-HolidayParty2015.swf',
          dance: 'archives:RoomsDance-HolidayParty2015.swf',
          pet: 'archives:RoomsPet-HolidayParty2015.swf',
          pizza: 'archives:RoomsPizza-HolidayParty2015.swf',
          plaza: 'archives:RoomsPlaza-HolidayParty2015.swf',
          hotellobby: 'archives:RoomsHotellobby-HolidayParty2015.swf',
          hotelroof: 'archives:RoomsHotelroof-HolidayParty2015.swf',
          hotelspa: 'archives:RoomsHotelspa-HolidayParty2015.swf',
          park: 'archives:RoomsPark-HolidayParty2015.swf',
          pufflewild: 'archives:RoomsPufflewild-HolidayParty2015.swf',
          school: 'archives:RoomsSchool-HolidayParty2015.swf',
          skatepark: 'archives:RoomsSkatepark-HolidayParty2015.swf',
          mtn: 'archives:RoomsMtn-HolidayParty2015.swf',
          lodge: 'archives:RoomsLodge-HolidayParty2015.swf',
          village: 'archives:RoomsVillage-HolidayParty2015.swf',
          dojosnow: 'archives:RoomsDojosnow-HolidayParty2015.swf',
          town: 'archives:RoomsTown-HolidayParty2015.swf',
          party3: 'archives:RoomsParty3-HolidayParty2015.swf'
        },
        music: {
          forts: 1073,
          party1: 1078,
          party14: 1080,
          beacon: 583,
          book: 1070,
          shipquarters: 1083,
          shop: 1086,
          cloudforest: 363,
          coffee: 1070,
          cove: 1071,
          shipnest: 1082,
          dock: 1072,
          dojo: 403,
          dojoext: 404,
          agentlobbymulti: 922,
          dojofire: 405,
          forest: 1088,
          rink: 592,
          berg: 1069,
          light: 588,
          attic: 884,
          lounge: 1075,
          party13: 1091,
          mall: 1076,
          shack: 1090,
          dance: 1087,
          pet: 659,
          pizza: 1081,
          plaza: 1089,
          hotellobby: 362,
          hotelroof: 360,
          hotelspa: 361,
          park: 658,
          pufflewild: 897,
          school: 1085,
          skatepark: 754,
          mtn: 1077,
          lodge: 1074,
          village: 1077,
          dojosnow: 407,
          town: 1084
        },
        localChanges: {
          'close_ups/quest_interface.swf': { en: 'archives:Close_upsQuest_interface-HolidayParty2015.swf' }
        },
        globalChanges: {
          'close_ups/membership.swf': 'archives:2015AdventCalendarmembership.swf',
          'membership/party2.swf': 'archives:MembershipParty2-HolidayParty2015.swf',
          'membership/party3.swf': 'archives:MembershipParty3-HolidayParty2015.swf',
          'content/party_icon.swf': 'archives:2015AdventCalendarpartyicon.swf',
          'close_ups/interface.swf': 'archives:2015AdventCalendarinterface.swf',
          'close_ups/character_dialogue_december_congrats.swf': 'archives:Close_upsCharacter_dialogue_december_congrats-HolidayParty2015.swf',
          'close_ups/character_dialogue_december_login.swf': 'archives:Close_upsCharacter_dialogue_december_login-HolidayParty2015.swf',
          'close_ups/character_dialogue_walrus_collect.swf': 'archives:Close_upsCharacter_dialogue_walrus_collect-HolidayParty2015.swf',
          'close_ups/item_calendar.swf': 'archives:Close_upsItem_calendar_web-HolidayParty2015.swf',
          'content/features.swf': 'archives:ContentFeatures-HolidayParty2015.swf',
          'content/logo.swf': 'archives:ContentLogo-HolidayParty2015.swf',
          'close_ups/login.swf': 'archives:2015AdventCalendarlogin.swf',
          'telescope/telescope.swf': 'archives:Telescope-HolidayParty2015.swf',
          'binoculars/binoculars.swf': 'archives:Binoculars-HolidayParty2015.swf'
        },
        fileChanges: {
          'play/v2/client/interface.swf': 'archives:ClientInterface-HolidayParty2015.swf',
          'play/v2/content/global/rooms/effects/avatar.swf': 'archives:RoomsEffectsAvatar-HolidayParty2015.swf',
          'play/v2/client/party.swf': 'archives:ClientParty-HolidayParty2015.swf'
        },
        coinsForChange: true
      }
    }
  }
];
